### YamlMime:PowershellCmdlet
summary: |-
  Returns app acquisition settings.
module: sharepoint-server
notes: ""
inputs:
- name: <xref href="Microsoft.SharePoint.PowerShell.SPWebApplicationPipeBind" data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.SharePoint.PowerShell.SPSiteSubscriptionPipeBind
    Microsoft.SharePoint.PowerShell.SPAssignmentCollection
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Set-SPAppAcquisitionConfiguration
  href: Set-SPAppAcquisitionConfiguration.yml
syntaxes:
- >-
  Get-SPAppAcquisitionConfiguration -SiteSubscription <SPSiteSubscriptionPipeBind>
   [-AssignmentCollection <SPAssignmentCollection>] [<CommonParameters>]
- >-
  Get-SPAppAcquisitionConfiguration [-AssignmentCollection <SPAssignmentCollection>]
   -WebApplication <SPWebApplicationPipeBind> [<CommonParameters>]
examples:
- title: '------------EXAMPLE 1-------'
  code: |-
    Get-SPAppAcquisitionConfiguration -WebApplication https://localhost
  description: |-
    This example returns app acquisition settings for the specified web application.
  summary: ""
- title: '------------EXAMPLE 2-------'
  code: |-
    Get-SPAppAcquisitionConfiguration -SiteSubscription https://localhost/sites/SharePointOnlineAdmin
  description: |-
    This example returns app acquisition settings for the specified tenant.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal. Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management. Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory. When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store. If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPSiteSubscriptionPipeBind" data-throw-if-not-resolved="False" />
  name: SiteSubscription
  isRequired: true
  description: |+
    Specifies the site collection for which app acquisition settings are to be returned.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPWebApplicationPipeBind" data-throw-if-not-resolved="False" />
  name: WebApplication
  isRequired: true
  description: |+
    Specifies the web application for which app acquisition settings are to be returned.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.Get-SPAppAcquisitionConfiguration
name: Get-SPAppAcquisitionConfiguration
description: |-
  This cmdlet contains more than one parameter set.
  You may only use parameters from one parameter set, and you may not combine parameters from different parameter sets.
  For more information about how to use parameter sets, see Cmdlet Parameter Sets [https://go.microsoft.com/fwlink/?LinkID=187810](https://go.microsoft.com/fwlink/?LinkID=187810).

  Use the `Get-SPAppAcquisitionConfiguration` cmdlet to return app acquisition settings from the SharePoint Storeor App Catalog.
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/get-spappacquisitionconfiguration
  applicable: SharePoint Server Subscription Edition
  title: Get-SPAppAcquisitionConfiguration
  PlatyPS schema version: 2.0.0
