### YamlMime:PowershellCmdlet
summary: |-
  Returns the hosting quotas for an app.
module: sharepoint-server
notes: ""
inputs:
- name: <xref href="Microsoft.SharePoint.PowerShell.SPSiteSubscriptionPipeBind" data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.SharePoint.PowerShell.SPAssignmentCollection
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Set-SPAppHostingQuotaConfiguration
  href: Set-SPAppHostingQuotaConfiguration.yml
syntaxes:
- >-
  Get-SPAppHostingQuotaConfiguration [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-WhatIf]
   -SiteSubscription <SPSiteSubscriptionPipeBind> [<CommonParameters>]
examples:
- title: '--------------EXAMPLE 1---------'
  code: |-
    Get-SPAppHostingQuotaConfiguration -Identity '586d4a32-98c3-42ce-80be-3c76c10c250c'
  description: |-
    This example returns the hosted app quota associated to SiteSubscriptionID "586d4a32-98c3-42ce-80be-3c76c10c250c".
  summary: ""
- title: '--------------EXAMPLE 1---------'
  code: |-
    Get-SPSiteSubscription | Get-SPAppHostingQuotaConfiguration -Identity $_
  description: |-
    This example returns the hosted app quota associated for all site subscriptions in the farm.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal. Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management. Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory. When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store. If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPSiteSubscriptionPipeBind" data-throw-if-not-resolved="False" />
  name: SiteSubscription
  isRequired: true
  description: |+
    Specifies the site subscription from which to get site collections.

    The type must be a valid URL, in the form, https://server_name or a valid GUID (for example, 12345678-90ab-cdef-1234-567890bcdefgh).

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.Get-SPAppHostingQuotaConfiguration
name: Get-SPAppHostingQuotaConfiguration
description: |-
  Use the `Get-SPAppHostingQuotaConfiguration` cmdlet to return the hosting quotas for a specified app by using the Identity parameter.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at Windows PowerShell for SharePoint Server 2016, SharePoint Server 2019 reference [https://go.microsoft.com/fwlink/p/?LinkId=671715](https://go.microsoft.com/fwlink/p/?LinkId=671715).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/get-spapphostingquotaconfiguration
  applicable: SharePoint Server Subscription Edition
  title: Get-SPAppHostingQuotaConfiguration
  PlatyPS schema version: 2.0.0
