### YamlMime:PowershellCmdlet
summary: |-
  Retrieves information about the search service application backup files.
module: sharepoint-server
notes: ""
syntaxes:
- >-
  Get-SPEnterpriseSearchServiceApplicationBackupStore [-BackupFolder] <String> [-Name] <String>
   [[-BackupId] <String>] [-UseMostRecent] [-IsVerbose] [-AssignmentCollection <SPAssignmentCollection>]
   [-Confirm] [-WhatIf] [<CommonParameters>]
examples:
- title: '------------------EXAMPLE 1-----------------'
  code: |-
    Get-SPEnterpriseSearchServiceApplicationBackupStore -BackupFolder \\sample\backup -Name "Search Service Application" -BackupId 3222ad97-91ad-471f-a764-780ec1f05f74
  description: |-
    This example retrieves the backup of the search databases and index files that are located at \\\\sample\backup with the backup id 3222ad97-91ad-471f-a764-780ec1f05f74 from the search service application Search Service Application.
  summary: ""
- title: '------------------EXAMPLE 2-----------------'
  code: |-
    Get-SPEnterpriseSearchServiceApplicationBackupStore -BackupFolder \\sample\backup -Name "Search Service Application" -UseMostRecent
  description: |-
    This example retrieves the most recently taken backup of the search databases and index files that are located at \\\\sample\backup from the search service application Search Service Application.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: BackupFolder
  isRequired: true
  description: |+
    Specifies the full file path of the backup files.

  defaultValue: None
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: BackupId
  description: |+
    Specifies the GUID of the backup in the referred package.

  defaultValue: None
  pipelineInput: true
  position: "4"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: IsVerbose
  description: |+
    A switch to specify if messages should be printed out when the cmdlet is running.

  defaultValue: None
  position: "6"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the search service application from which to retrieve the related backup information.



  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: UseMostRecent
  description: |+
    A switch to specify if the most recent backup should be used.

  defaultValue: None
  position: "5"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.Get-SPEnterpriseSearchServiceApplicationBackupStore
name: Get-SPEnterpriseSearchServiceApplicationBackupStore
description: |-
  This cmdlet returns information about the search databases and index files in a specified search service application backup location.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.Office.Server.Search.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/get-spenterprisesearchserviceapplicationbackupstore
  applicable: SharePoint Server Subscription Edition
  title: Get-SPEnterpriseSearchServiceApplicationBackupStore
  PlatyPS schema version: 2.0.0
