### YamlMime:PowershellCmdlet
summary: |-
  Returns a Secure Store application.
module: sharepoint-server
notes: ""
syntaxes:
- >-
  Get-SPSecureStoreApplication -Name <String> -ServiceContext <SPServiceContextPipeBind>
   [-AssignmentCollection <SPAssignmentCollection>] [<CommonParameters>]
- >-
  Get-SPSecureStoreApplication -ServiceContext <SPServiceContextPipeBind>
   [-AssignmentCollection <SPAssignmentCollection>] [-All] [<CommonParameters>]
examples:
- title: '------------------EXAMPLE 1------------------'
  code: |-
    $ssApp = Get-SPSecureStoreApplication -ServiceContext http://contoso -Name "ContosoTargetApplication"
  description: |-
    This example gets the Secure Store application for the target application with the name ContosoTargetApplication.
  summary: ""
- title: '------------------EXAMPLE 2------------------'
  code: |-
    Get-SPSecureStoreApplication -ServiceContext http://contoso -All
  description: |-
    This example returns all of the Secure Store applications http://contoso.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: All
  isRequired: true
  description: |+
    Returns all secure store applications for the given Service Context.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal. Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management. Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory. When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store. If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the Secure Store application to get.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPServiceContextPipeBind" data-throw-if-not-resolved="False" />
  name: ServiceContext
  isRequired: true
  description: |+
    Specifies the service context for the local Secure Store application to connect to.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.Get-SPSecureStoreApplication
name: Get-SPSecureStoreApplication
description: |-
  This cmdlet contains more than one parameter set.
  You may only use parameters from one parameter set, and you may not combine parameters from different parameter sets.
  For more information about how to use parameter sets, see [Cmdlet parameter sets](https://learn.microsoft.com/powershell/scripting/developer/cmdlet/cmdlet-parameter-sets).

  The Get-SPSecureStoreApplication cmdlet returns a Secure Store application.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/get-spsecurestoreapplication
  applicable: SharePoint Server Subscription Edition
  title: Get-SPSecureStoreApplication
  PlatyPS schema version: 2.0.0
