### YamlMime:PowershellCmdlet
summary: |-
  Adds a new security principal to an SPObjectSecurity object.
module: sharepoint-server
notes: ""
syntaxes:
- >-
  Grant-SPObjectSecurity [-Identity] <SPObjectSecurity> [-Principal] <SPClaim> [-Rights] <String[]>
   [-AssignmentCollection <SPAssignmentCollection>] [-Replace] [<CommonParameters>]
examples:
- title: '------------------EXAMPLE------------------'
  code: |-
    $principal = New-SPClaimsPrincipal "CONTOSO\JaneDoe" -IdentityType WindowsSamAccountName 
    $sa = Get-SPServiceApplication | ?{$_.TypeName -eq 'User Profile Service Application'}
    $security = Get-SPServiceApplicationSecurity $sa -Admin
    Grant-SPObjectSecurity $security $principal "Full Control"
    Set-SPServiceApplicationSecurity $sa -Admin $security
  description: |-
    This example retrieves the SPObjectSecurity object corresponding to the administrator ACL on the User Profile Service Application and adds a new user principal to that ACL.

    The new user is an administrator for the service application $serviceApp.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPObjectSecurity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Specifies the SPObjectSecurity object to which the new security principal is added.
    You can use the Get-SPServiceApplicationSecurity cmdlet to get a SPObjectSecurity object .

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPClaim" data-throw-if-not-resolved="False" />
  name: Principal
  isRequired: true
  description: |+
    Specifies the principal to whom the rights apply.

    The type must a valid name a principal; for example, Full Control.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Replace
  description: |+
    Replaces the existing rights on the SPObjectSecurity object with the new rights specified.
    If this parameter is not specified, the new rights are added to the existing rights.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Rights
  isRequired: true
  description: |+
    Specifies the rights granted to the principal.

    The type must a valid array of strings that represents the rights granted to the principal.

  defaultValue: None
  position: "3"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.Grant-SPObjectSecurity
name: Grant-SPObjectSecurity
description: |-
  The Grant-SPObjectSecurity cmdlet adds a new security principal, such as a user, to a SPObjectSecurity object.
  An SPObjectSecurity object is a common object that is used to represent the security access control list (ACL) of SharePoint administrative objects, in particular, service applications.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/grant-spobjectsecurity
  applicable: SharePoint Server Subscription Edition
  title: Grant-SPObjectSecurity
  PlatyPS schema version: 2.0.0
