### YamlMime:PowershellCmdlet
summary: |-
  Creates a new content deployment path.
module: sharepoint-server
notes: ""
syntaxes:
- >-
  New-SPContentDeploymentPath -DestinationCentralAdministrationURL <Uri> -DestinationSPSite <String>
   -DestinationSPWebApplication <Uri> -Name <String> -PathAccount <PSCredential> -SourceSPSite <SPSitePipeBind>
   -SourceSPWebApplication <SPWebApplicationPipeBind> [-AssignmentCollection <SPAssignmentCollection>]
   [-Authentication <PathAuthenticationOption>] [-CompressionEnabled] [-Confirm]
   [-DeploySecurityInformation <SPIncludeSecurity>] [-DeployUserNamesEnabled] [-Description <String>]
   [-EventReceiversEnabled] [-KeepTemporaryFilesOptions <TemporaryFilesOption>] [-PathEnabled] [-WhatIf]
   [<CommonParameters>]
examples:
- title: '-----------------EXAMPLE----------------------'
  code: |-
    $source = Get-SPSite "http://source/"
    $credentials=Get-Credential
    New-SPContentDeploymentPath -Name "Deployment Path" -SourceSPWebApplication $source.WebApplication -SourceSPSite $source DestinationCentralAdministrationURL "http://destination:8080" -DestinationSPWebApplication "http://destination" -DestinationSPSite "http://destination" -KeepTemporaryFilesOptions "Failure" -PathAccount $credentials -PathEnabled:$true
  description: |-
    This example creates a new deployment path called Deployment Path that connects a source at http://source to a destination at http://destination.
    The path is enabled and configured to keep temporary files on job failure.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="PathAuthenticationOption" data-throw-if-not-resolved="False" />
  name: Authentication
  description: |+
    Sets the Windows-based authentication type that the source front-end Web server uses to communicate with the destination Web application.

    The type must be one of the following values: WindowsAuth or BasicAuth.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: CompressionEnabled
  description: |+
    Turns on compression during the export.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPIncludeSecurity" data-throw-if-not-resolved="False" />
  name: DeploySecurityInformation
  description: |+
    Specifies the user and group information to include during the export operation for this content deployment path.
    The default value is All.

    The type must be one of the following values: None, All, or WssOnly- Applies only SharePoint Foundation security settings.
    Includes user memberships and role assignments such as default roles, for example, Web Designer or any custom roles that extend from the default roles.
    The access control list (ACL) for each object is migrated.
    No user information defined in the DAP or LDAP servers is included.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DeployUserNamesEnabled
  description: |+
    Specifies whether to include user names during a deployment.

    Valid values are one of the following:

    - $True Retains the original author and editor information, time and date stamp, and user lookup value.
    - $False Retains the original date and time stamp, but replaces the author and editor data with the System Account, and replaces the user lookup value with an empty string ("").

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Description
  description: |+
    Sets the description for the content deployment path.
    The description can contain a maximum of 4096 alphanumeric characters.

    The type must be a valid string.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Uri" data-throw-if-not-resolved="False" />
  name: DestinationCentralAdministrationURL
  isRequired: true
  description: |+
    Specifies the SharePoint Central Administration URL for the destination farm.

    The type must be a valid URL, in the form http://server_name.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DestinationSPSite
  isRequired: true
  description: |+
    Specifies the destination site collection.

    The type must be a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; a valid URL, in the form http://server_name; or an instance of a valid SPSite object.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Uri" data-throw-if-not-resolved="False" />
  name: DestinationSPWebApplication
  isRequired: true
  description: |+
    Specifies the destination Web application.

    The type must be a valid URL, in the form http://server_name; a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; a valid name of Web application (for example, MyOfficeApp1); or an instance of a valid SPWebApplication object.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: EventReceiversEnabled
  description: |+
    Turns on event receivers during import.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="TemporaryFilesOption" data-throw-if-not-resolved="False" />
  name: KeepTemporaryFilesOptions
  description: |+
    Specifies that temporary files are kept after content deployment is finished.

    The type must be one of the following values: Never, Always, or OnFailure.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the new content deployment path.

    The type must be a valid name of a content deployment path; for example, DeployPath1.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
  name: PathAccount
  isRequired: true
  description: |+
    Specifies the user ID that is an administrator on the Central Administration page on the destination farm.

    The type must be a valid SharePoint user.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PathEnabled
  description: |+
    Enables the new content deployment path.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPSitePipeBind" data-throw-if-not-resolved="False" />
  name: SourceSPSite
  isRequired: true
  description: |+
    Specifies the source site collection for the deployment path.
    Must be a site collection in the source specified in the SourceSPWebApplication parameter.

    The type must be a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; a valid URL, in the form http://server_name; or an instance of a valid SPSite object.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPWebApplicationPipeBind" data-throw-if-not-resolved="False" />
  name: SourceSPWebApplication
  isRequired: true
  description: |+
    Specifies the source Web application for the deployment path.

    The type must be a valid URL, in the form http://server_name; a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; a valid name of SharePoint Web application (for example, MyOfficeApp1); or an instance of a valid SPWebApplication object.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.New-SPContentDeploymentPath
name: New-SPContentDeploymentPath
description: |-
  The New-SPContentDeploymentPath cmdlet adds a new content deployment path for a content deployment job.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.SharePoint.Publishing.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/new-spcontentdeploymentpath
  applicable: SharePoint Server Subscription Edition
  title: New-SPContentDeploymentPath
  PlatyPS schema version: 2.0.0
