### YamlMime:PowershellCmdlet
summary: |-
  Provisions a new instance of the Machine Translation service.
module: sharepoint-server
notes: ""
links:
- text: Set-SPTranslationServiceApplication
  href: Set-SPTranslationServiceApplication.yml
- text: New-SPTranslationServiceApplicationProxy
  href: New-SPTranslationServiceApplicationProxy.yml
- text: Set-SPTranslationServiceApplicationProxy
  href: Set-SPTranslationServiceApplicationProxy.yml
syntaxes:
- >-
  New-SPTranslationServiceApplication [-Name] <String> -ApplicationPool <SPIisWebServiceApplicationPoolPipeBind>
   [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-DatabaseCredential <PSCredential>]
   [-DatabaseName <String>] [-DatabaseServer <String>] [-Default] [-FailoverDatabaseServer <String>]
   [-PartitionMode] [-WhatIf] [-DeferUpgradeActions] [<CommonParameters>]
examples:
- title: '-------------EXAMPLE---------------'
  code: |-
    New-SPTranslationServiceApplication -Name TranslationService -ApplicationPool 'SharePoint Web Services Default' -DatabaseServer Server1 -DatabaseName TranslationServiceDatabase
  description: |-
    This example creates a Machine Translation service application named TranslationService which will run in the SharePoint Web Services Default service application pool.
    The database will be called TranslationServiceDatabase and will be hosted on the Server1 SQL server instance.
  summary: ""
parameters:
- type: <xref href="SPIisWebServiceApplicationPoolPipeBind" data-throw-if-not-resolved="False" />
  name: ApplicationPool
  isRequired: true
  description: |+
    Specifies the managed application pool that the instance of Translation Service will run in.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
  name: DatabaseCredential
  description: |+
    Specifies the SQL Server credentials used for this Translation Service instance.
    This parameter to be used only used for SQL authentication; if not present, Windows authentication is used instead.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DatabaseName
  description: |+
    Specifies the database name which is to be used for this Translation Service instance.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DatabaseServer
  description: |+
    Specifies the database server which is to be used for this Translation Service instance.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Default
  description: |+
    Determines whether or not the proxy for this service application should be added to the default proxy group for this Web application.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DeferUpgradeActions
  description: |+
    Specifies if the upgrade process is to be deferred and manually completed.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FailoverDatabaseServer
  description: |+
    Specifies the SQL server instance that will be used as a backup to the primary SQL Server instance.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the unique identifier of Translation Service instance to be created.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PartitionMode
  description: |+
    Restricts this service to behave uniquely on a partitioned set of site collections.
    This cannot be changed after the application is provisioned.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.New-SPTranslationServiceApplication
name: New-SPTranslationServiceApplication
description: |-
  Use the `New-SPTranslationServiceApplication` cmdlet to provision a new instance of the Machine Translation service on the farm.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.Office.TranslationServices.dll-Help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/new-sptranslationserviceapplication
  applicable: SharePoint Server Subscription Edition
  title: New-SPTranslationServiceApplication
  PlatyPS schema version: 2.0.0
