### YamlMime:PowershellCmdlet
summary: |-
  Creates a new Secure Store application.
module: sharepoint-server
notes: ""
syntaxes:
- >-
  New-SPSecureStoreApplication -ServiceContext <SPServiceContextPipeBind> -TargetApplication <TargetApplication>
   [-Administrator <SPClaim[]>] [-AssignmentCollection <SPAssignmentCollection>]
   [-CredentialsOwnerGroup <SPClaim[]>] -Fields <TargetApplicationField[]> [-TicketRedeemer <SPClaim[]>]
   [<CommonParameters>]
examples:
- title: '------------------EXAMPLE------------------'
  code: |-
    $usernameField = New-SPSecureStoreApplicationField -Name "UserName" -Type WindowsUserName -Masked:$false
    $passwordField = New-SPSecureStoreApplicationField -Name "Password" -Type WindowsPassword -Masked:$true
    $fields = $usernameField,$passwordField
    $userClaim = New-SPClaimsPrincipal -Identity "CONTOSO\janedoe" -IdentityType WindowsSamAccountName
    $contosoTargetApp = New-SPSecureStoreTargetApplication -Name "ContosoTargetApplication" -FriendlyName "Contoso Target Application" -ApplicationType Group
    New-SPSecureStoreApplication -ServiceContext http://contoso -TargetApplication $contosoTargetApp -Fields $fields -Administrator $userClaim
  description: |-
    This example creates a new group target application ContosoTargetApplication and then a new application for that target application. This new application has two fields; UserName of type WindowsUserName and Password of type WindowsPassword. The user with identity janedoe on the CONTOSO domain is set as the target application administrator.
  summary: ""
parameters:
- type: <xref href="SPClaim" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Administrator
  description: |+
    Specifies the administrator of the new Secure Store application.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPClaim" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CredentialsOwnerGroup
  description: |+
    Specifies the claims object for the groups that own the group credentials.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="TargetApplicationField" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Fields
  isRequired: true
  description: |+
    Specifies the field information for the application.
    The default fields are username and password.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPServiceContextPipeBind" data-throw-if-not-resolved="False" />
  name: ServiceContext
  isRequired: true
  description: |+
    Specifies the service context for the target application.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="TargetApplication" data-throw-if-not-resolved="False" />
  name: TargetApplication
  isRequired: true
  description: |+
    Specifies information about the target application.
    For example, the TargetApplication object includes data values for application name, display name, contact info, enable ticketing flag and URL address to set the credential.
    The schema for the TargetApplication object is defined in the ISecureSToreProviderExtended interface that exposes the target application metadata.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPClaim" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: TicketRedeemer
  description: |+
    Specifies the ticket redeemer claim value.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.New-SPSecureStoreApplication
name: New-SPSecureStoreApplication
description: |-
  The `New-SPSecureStoreApplication` cmdlet creates a new Secure Store application.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/new-spsecurestoreapplication
  applicable: SharePoint Server Subscription Edition
  title: New-SPSecureStoreApplication
  PlatyPS schema version: 2.0.0
