### YamlMime:PowershellCmdlet
summary: |-
  Creates a PowerPoint Conversion Service application.
module: sharepoint-server
notes: ""
links:
- text: New-SPPowerPointConversionServiceApplicationProxy
  href: New-SPPowerPointConversionServiceApplicationProxy.yml
- text: Set-SPPowerPointConversionServiceApplication
  href: Set-SPPowerPointConversionServiceApplication.yml
syntaxes:
- >-
  New-SPPowerPointConversionServiceApplication [-Name] <String>
   -ApplicationPool <SPIisWebServiceApplicationPoolPipeBind> [-AssignmentCollection <SPAssignmentCollection>]
   [-Confirm] [-WhatIf] [<CommonParameters>]
examples:
- title: Example
  code: |-
    New-SPPowerPointConversionServiceApplication -Name "PowerPoint Conversion Service Application" -ApplicationPool "SharePoint Web Services Default"
  description: |-
    This example creates a new instance of the PowerPoint Conversion Service application named _PowerPoint Conversion Service Application_ and assigns it to the default application pool.
  summary: ""
parameters:
- type: <xref href="SPIisWebServiceApplicationPoolPipeBind" data-throw-if-not-resolved="False" />
  name: ApplicationPool
  isRequired: true
  description: |+
    Assigns an application pool that Internet Information Services (IIS) will use for this service application.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the PowerPoint Conversion Service application.

  defaultValue: None
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.New-SPPowerPointConversionServiceApplication
name: New-SPPowerPointConversionServiceApplication
description: |-
  Use the `New-SPPowerPointConversionServiceApplication` cmdlet to create a new instance of a PowerPoint Conversion Service application by using the Name parameter.

  After the PowerPoint Conversion Service application is created, you can convert PowerPoint presentations to various formats.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.Office.Server.Powerpoint.dll-Help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/new-sppowerpointconversionserviceapplication
  applicable: SharePoint Server Subscription Edition
  title: New-SPPowerPointConversionServiceApplication
  PlatyPS schema version: 2.0.0
