### YamlMime:PowershellCmdlet
summary: |-
  Creates a Machine Translation Service application proxy on the local farm.
module: sharepoint-server
notes: ""
links:
- text: New-SPTranslationServiceApplication
  href: New-SPTranslationServiceApplication.yml
- text: Set-SPTranslationServiceApplication
  href: Set-SPTranslationServiceApplication.yml
- text: Set-SPTranslationServiceApplicationProxy
  href: Set-SPTranslationServiceApplicationProxy.yml
syntaxes:
- >-
  New-SPTranslationServiceApplicationProxy -Name <String>
   -ServiceApplication <TranslationServiceApplicationPipeBind> [-AssignmentCollection <SPAssignmentCollection>]
   [-Confirm] [-DefaultProxyGroup] [-PartitionMode] [-WhatIf] [<CommonParameters>]
- >-
  New-SPTranslationServiceApplicationProxy -Name <String> -Uri <String>
   [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-DefaultProxyGroup] [-PartitionMode] [-WhatIf]
   [<CommonParameters>]
examples:
- title: '-----------EXAMPLE---------'
  code: |-
    $sa = New-SPTranslationServiceApplication -Name TranslationService -ApplicationPool 'SharePoint Web Services Default' -DatabaseServer Server1 -DatabaseName TranslationServiceDatabase
    New-SPTranslationServiceApplicationProxy -Name TranslationServiceProxy -ServiceApplication $sa -DefaultProxyGroup
  description: |-
    This example creates a Machine Translation Service application and proxy in the default proxy group named TranslationServiceProxy.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DefaultProxyGroup
  description: |+
    Specifies that the Machine Translation Service application proxy be added to the default proxy group for the local farm.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the display name for the new Machine Translation Service application.
    The name that you use must be a unique name of a Machine Translation Service application in this farm.
    The name can be a maximum of 128 characters.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PartitionMode
  description: |+
    Specifies that the service application restrict data by site group.
    After the PartitionMode parameter is set and the service application is created, it cannot be changed.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="TranslationServiceApplicationPipeBind" data-throw-if-not-resolved="False" />
  name: ServiceApplication
  isRequired: true
  description: |+
    Specifies the local Machine Translation Service application that is associated with the new proxy.

    The type must be a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; a valid name of a Machine Translation Service application (for example, MachTrans1); or an instance of a valid SPServiceApplication object.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Uri
  isRequired: true
  description: |+
    Specifies the URI of the remote machine translation service application this proxy should communicate with.
    This value is required only if you plan to connect a Machine Translation Service application from a remote farm.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.New-SPTranslationServiceApplicationProxy
name: New-SPTranslationServiceApplicationProxy
description: |-
  This cmdlet contains more than one parameter set.
  You may only use parameters from one parameter set and you may not combine parameters from different parameter sets.
  For more information about how to use parameter sets, see [Cmdlet parameter sets](https://learn.microsoft.com/powershell/scripting/developer/cmdlet/cmdlet-parameter-sets).

  The `New-SPTranslationServiceApplicationProxy` cmdlet creates a Machine Translation Service application proxy on the local farm.
  The proxy is added to the default proxy group for the local farm.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.Office.TranslationServices.dll-Help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/new-sptranslationserviceapplicationproxy
  applicable: SharePoint Server Subscription Edition
  title: New-SPTranslationServiceApplicationProxy
  PlatyPS schema version: 2.0.0
