### YamlMime:PowershellCmdlet
summary: |-
  Creates an AppDomain entry.
module: sharepoint-server
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.SharePoint.PowerShell.SPAssignmentCollection
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-SPWebApplicationAppDomain
  href: Get-SPWebApplicationAppDomain.yml
- text: Remove-SPWebApplicationAppDomain
  href: Remove-SPWebApplicationAppDomain.yml
syntaxes:
- >-
  New-SPWebApplicationAppDomain [-AppDomain] <String> -WebApplication <SPWebApplicationPipeBind>
   [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-Port <Int32>] [-SecureSocketsLayer] [-WhatIf]
   [-Zone <SPUrlZone>] [<CommonParameters>]
examples:
- title: '------------------EXAMPLE 1-----------------------'
  code: |-
    New-SPWebApplicationAppDomain -AppDomain contosoapps.com -WebApplication https://www.contoso.com
  description: |-
    Creates a new app domain for apps for SharePoint for the specified web application in the default zone.
  summary: ""
- title: '------------------EXAMPLE 2-----------------------'
  code: |-
    New-SPWebApplicationAppDomain -AppDomain contosoapps.com -WebApplication https://www.contoso.com -Zone Internet -Port 10000
  description: |-
    Creates a new app domain for apps for SharePoint for the specified web application in the internet zone at port 10000.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AppDomain
  isRequired: true
  description: |+
    Specifies the URI of the app domain.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal. Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management. Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory. When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store. If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Port
  description: |+
    Specifies the IIS port number to which the app domain will be assigned. If no value is specified, the same port used by the web application for the zone is applied.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: SecureSocketsLayer
  description: |+
    Specifies that the app domain will use Secured Sockets Layer (SSL) security. If no value is specified, no SSL security will be used.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPWebApplicationPipeBind" data-throw-if-not-resolved="False" />
  name: WebApplication
  isRequired: true
  description: |+
    Specifies the GUID, URI, or name of the web application for which the app domain is being configured.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPUrlZone" data-throw-if-not-resolved="False" />
  name: Zone
  description: |+
    Specifies the security zone to which the app domain will be assigned.

    * Default

    * Intranet

    * Internet

    * Extranet

    * Custom

    If no value is specified, Default is applied.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.New-SPWebApplicationAppDomain
name: New-SPWebApplicationAppDomain
description: |-
  Use the New-SPWebApplicationAppDomain cmdlet to create an AppDomain entry. If you specify a port, the cmdlet adds a port binding to the Internet Information Services (IIS) site corresponding to the Web Application/Zone combination.
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/new-spwebapplicationappdomain
  applicable: SharePoint Server Subscription Edition
  title: New-SPWebApplicationAppDomain
  PlatyPS schema version: 2.0.0
