### YamlMime:PowershellCmdlet
summary: |-
  Adds a User Profile Service Application to a farm.
module: sharepoint-server
notes: ""
syntaxes:
- >-
  New-SPProfileServiceApplication -ApplicationPool <SPIisWebServiceApplicationPoolPipeBind> [-Name <String>]
   [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-MySiteHostLocation <SPSitePipeBind>]
   [-PartitionMode] [-ProfileDBCredentials <PSCredential>] [-ProfileDBName <String>] [-ProfileDBServer <String>]
   [-ProfileSyncDBCredentials <PSCredential>] [-ProfileDBFailoverServer <String>] [-ProfileSyncDBName <String>]
   [-ProfileSyncDBServer <String>] [-ProfileSyncDBFailoverServer <String>] [-SocialDBCredentials <PSCredential>]
   [-SocialDBName <String>] [-SocialDBServer <String>] [-SocialDBFailoverServer <String>] [-WhatIf]
   [-DeferUpgradeActions] [<CommonParameters>]
- >-
  New-SPProfileServiceApplication -ApplicationPool <SPIisWebServiceApplicationPoolPipeBind> [-Name <String>]
   [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] -MySiteHostLocation <SPSitePipeBind>
   [-MySiteManagedPath <SPPrefixPipeBind>] [-PartitionMode] [-ProfileDBCredentials <PSCredential>]
   [-ProfileDBName <String>] [-ProfileDBServer <String>] [-ProfileSyncDBCredentials <PSCredential>]
   [-ProfileDBFailoverServer <String>] [-ProfileSyncDBName <String>] [-ProfileSyncDBServer <String>]
   [-ProfileSyncDBFailoverServer <String>] [-SiteNamingConflictResolution <String>]
   [-SocialDBCredentials <PSCredential>] [-SocialDBName <String>] [-SocialDBServer <String>]
   [-SocialDBFailoverServer <String>] [-WhatIf] [-DeferUpgradeActions] [<CommonParameters>]
examples:
- title: '------------------EXAMPLE------------------'
  code: |-
    New-SPProfileServiceApplication -Name 'User Profile Service Application' -ApplicationPool 'SharePoint Web Services Default' -ProfileDBName Profile -SocialDBName Social -ProfileSyncDBname Sync
  description: |-
    This example creates a new User Profile Service application.
  summary: ""
parameters:
- type: <xref href="SPIisWebServiceApplicationPoolPipeBind" data-throw-if-not-resolved="False" />
  name: ApplicationPool
  isRequired: true
  description: |+
    Specifies the existing IIS application pool in which to run the Web service for the service application.

    The type must be a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; a valid name of an application pool (for example, AppPoolName1); or an instance of a valid IISWebServiceApplicationPool object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DeferUpgradeActions
  description: |+
    Specifies if the upgrade process is to be deferred and manually completed.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPSitePipeBind" data-throw-if-not-resolved="False" />
  name: MySiteHostLocation
  isRequired: true
  description: |+
    Specifies the site collection where the My Site will be created.

    The type must be a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; or a valid URL, in the form https://server_name; or an instance of a valid SPSite object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPPrefixPipeBind" data-throw-if-not-resolved="False" />
  name: MySiteManagedPath
  description: |+
    Specifies the managed path where personal sites will be created.

    The type must be a valid URL, in the form https://server_name.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the display name for the new User Profile Service application.
    The name must be a unique name of a User Profile Service application in this farm.
    The name can be a maximum of 64 characters.

    The type must be a valid name of a service application; for example, UserProfileSvcApp1.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PartitionMode
  description: |+
    Specifies that the service application restrict data by site group.
    After the PartitionMode parameter is set and the service application is created, it cannot be changed.

    This property has no effect on SharePoint Server 2019.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
  name: ProfileDBCredentials
  description: |+
    Specifies the set of security credentials, such as a user name and a password, that is used to connect to the User Profile database that this cmdlet creates.

    The type must be a valid PSCredential object.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ProfileDBFailoverServer
  description: |+
    Associates a content database with a specific failover server that is used in conjunction with SQL Server database mirroring.
    The server name is the required value.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ProfileDBName
  description: |+
    Specifies the name of the database where the User Profile database is created.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ProfileDBServer
  description: |+
    Specifies the database where the User Profile database will be created.

    The type must be a valid name of a SQL Server database; for example, ProfileAppDB1.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
  name: ProfileSyncDBCredentials
  description: |+
    Specifies the set of security credentials, such as a user name and a password, that will be used to connect to the Profile Sync database that is specified in the ProfileSyncDBName parameter.

    The type must be a valid PSCredential object.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ProfileSyncDBFailoverServer
  description: |+
    Associates a Profile Sync database with a specific failover server that is used in conjunction with SQL Server database mirroring.
    The server name is the required value.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ProfileSyncDBName
  description: |+
    Specifies the database where the Profile Sync database will be created.

    The type must be a valid name of a SQL Server database; for example, ProfileSyncAppDB1.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ProfileSyncDBServer
  description: |+
    Specifies the database server that will host the Profile Sync database that is specified in the ProfileSyncDBName parameter.

    The type must be a valid name of a SQL Server host; for example, SQLServerProfileSyncHost1.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SiteNamingConflictResolution
  description: |+
    Specifies the format to use to name personal sites.

    Use one of the following integer values:

    1   Personal site collections are to be based on user names without any conflict resolution.
    For example, https://portal_site/location/username/

    2   Personal site collections are to be based on user names with conflict resolution by using domain names.
    For example, .../username/ or .../domain_username/

    3   Personal site collections are to be named by using domain and user name always, to avoid any conflicts.
    For example, https://portal_site/location/domain_username/

    The default value is 1 (do not resolve conflicts).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
  name: SocialDBCredentials
  description: |+
    The set of security credentials, including a user name and a password, that is used to connect to the Social database that this cmdlet creates.

    The type must be a valid PSCredential object.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SocialDBFailoverServer
  description: |+
    Associates a Social database with a specific failover server that is used in conjunction with SQL Server database mirroring.
    The server name is the required value.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SocialDBName
  description: |+
    Specifies the database where the Social database will be created.

    The type must be a valid name of a SQL Server host; for example, SQLServerSocialHost1.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SocialDBServer
  description: |+
    Specifies the database server that will host the Social database that is specified in SocialDBName.

    The type must be a valid name of a SQL Server host; for example, SQLServerSocialHost1.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.New-SPProfileServiceApplication
name: New-SPProfileServiceApplication
description: |-
  This cmdlet contains more than one parameter set.

  You may only use parameters from one parameter set and you may not combine parameters from different parameter sets.
  For more information about how to use parameter sets, see [Cmdlet parameter sets](https://learn.microsoft.com/powershell/scripting/developer/cmdlet/cmdlet-parameter-sets).

  The `New-SPProfileServiceApplication` cmdlet adds and creates a new profile service application, or creates an instance of a profile service.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.Office.Server.UserProfiles.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/new-spprofileserviceapplication
  applicable: SharePoint Server Subscription Edition
  title: New-SPProfileServiceApplication
  PlatyPS schema version: 2.0.0
