### YamlMime:PowershellCmdlet
summary: |-
  Shares the specified local service application outside the farm.
module: sharepoint-server
notes: ""
syntaxes:
- >-
  Publish-SPServiceApplication [-Identity] <SPServiceApplicationPipeBind>
   [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-Description <String>] [-InfoLink <Uri>]
   [-WhatIf] [<CommonParameters>]
examples:
- title: '------------------EXAMPLE-----------------------'
  code: |-
    Publish-SPServiceApplication 053c34be-d251-488c-8e94-644eae94da26 -Description "Connect to this TestServiceApplcation of you want to use FeatureA in your farm" -InfoLink https://testurl
  description: |-
    This example publishes a service application to another farm.

    The service application GUID is unique to every farm.
    You can run the `Get-SPServiceApplication` cmdlet to see the GUID of the service applications and then use the result from the `Get-SPServiceApplication` cmdlet for other SPServiceApplication cmdlets; for example, `Grant-SPServiceApplication`.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Description
  description: |+
    Describes the service application to share outside the farm.
    If no value is specified, the value is left blank.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPServiceApplicationPipeBind" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Specifies the GUID of the service application to share outside the farm.

    The type must be a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Uri" data-throw-if-not-resolved="False" />
  name: InfoLink
  description: |+
    Specifies the link to more information about the service application to share outside the farm.
    If no link is specified, no link is made available.

    The type must be a valid URL, in the form  https://server_name/Site_Name/page_name.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.Publish-SPServiceApplication
name: Publish-SPServiceApplication
description: |-
  The `Publish-SPServiceApplication` cmdlet publishes the local service application, specified by the Identity parameter, outside the farm.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/publish-spserviceapplication
  applicable: SharePoint Server Subscription Edition
  title: Publish-SPServiceApplication
  PlatyPS schema version: 2.0.0
