### YamlMime:PowershellCmdlet
summary: |-
  Removes a User Settings Provider.
module: sharepoint-server
notes: ""
links:
- text: Get-SPUserSettingsProvider
  href: Get-SPUserSettingsProvider.yml
- text: New-SPUserSettingsProvider
  href: New-SPUserSettingsProvider.yml
- text: Get-SPUserSettingsProviderManager
  href: Get-SPUserSettingsProviderManager.yml
syntaxes:
- >-
  Remove-SPUserSettingsProvider [-Identity] <SPUserSettingsProviderPipeBind>
   [-AssignmentCollection <SPAssignmentCollection>] [<CommonParameters>]
examples:
- title: '----------------------EXAMPLE-----------------------'
  code: |-
    Remove-SPUserSettingsProvider -Identity "234bf0ed-70db-4158-a332-4dfd683b4148"
  description: |-
    This example removes a specific User Settings Provider by using the GUID, 234bf0ed-70db-4158-a332-4dfd683b4148.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPUserSettingsProviderPipeBind" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Specifies the GUID ID for a User Settings Provider to remove.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.Remove-SPUserSettingsProvider
name: Remove-SPUserSettingsProvider
description: |-
  Use the `Remove-SPUserSettingsProvider` cmdlet to remove a User Settings Provider from the farm.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/remove-spusersettingsprovider
  applicable: SharePoint Server Subscription Edition
  title: Remove-SPUserSettingsProvider
  PlatyPS schema version: 2.0.0
