### YamlMime:PowershellCmdlet
summary: |-
  Deletes the AppDomain.
module: sharepoint-server
notes: ""
inputs:
- name: <xref href="Microsoft.SharePoint.Administration.SPAppCmdlets.SPAppDomainPipeBind" data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.SharePoint.PowerShell.SPAssignmentCollection
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-SPWebApplicationAppDomain
  href: Get-SPWebApplicationAppDomain.yml
- text: New-SPWebApplicationAppDomain
  href: New-SPWebApplicationAppDomain.yml
syntaxes:
- >-
  Remove-SPWebApplicationAppDomain [-Identity] <SPAppDomainPipeBind>
   [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-WhatIf] [<CommonParameters>]
examples:
- title: '----------------------EXAMPLE 1-----------------------'
  code: |-
    Remove-SPWebApplicationAppDomain -WebApplication https://www.contoso.com
  description: |-
    Removes all of the app domains for the specified web application.
  summary: ""
- title: '----------------------EXAMPLE 2-----------------------'
  code: |-
    Remove-SPWebApplicationAppDomain -WebApplication https://www.contoso.com -Zone Internet
  description: |-
    Removes the app domains for the internet zone for the specified web application.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal. Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management. Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory. When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store. If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.


  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.


  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPAppDomainPipeBind" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Specifies the string of a domain name (that is, contoso.com) or a SPAppDomain object to remove.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.


  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.Remove-SPWebApplicationAppDomain
name: Remove-SPWebApplicationAppDomain
description: |-
  Use the Remove-SPWebApplicationAppDomain cmdlet to delete the AppDomain for a specified zone or to delete all the app domains for the web application if no zone is specified.

  This cmdlet also deletes the Internet Information Services (IIS) port binding if any was added for the WebApp/Zone combination.
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/remove-spwebapplicationappdomain
  applicable: SharePoint Server Subscription Edition
  title: Remove-SPWebApplicationAppDomain
  PlatyPS schema version: 2.0.0
