### YamlMime:PowershellCmdlet
summary: |-
  Restores the search index from the specified backup files.
module: sharepoint-server
notes: ""
syntaxes:
- >-
  Restore-SPEnterpriseSearchServiceApplicationIndex [-SearchApplication] <SearchServiceApplication>
   [-BackupFolder] <String> [-AllReplicas] [-AllowMove] [[-Retries] <Int32>] [[-RetryPauseSeconds] <Int32>]
   [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-WhatIf] [<CommonParameters>]
- >-
  Restore-SPEnterpriseSearchServiceApplicationIndex [-SearchApplication] <SearchServiceApplication>
   [-Handle] <String> [[-Retries] <Int32>] [[-RetryPauseSeconds] <Int32>]
   [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-WhatIf] [<CommonParameters>]
examples:
- title: '------------------EXAMPLE 1------------------'
  code: |-
    $ssa = Get-SPEnterpriseSearchServiceApplication
    $handle = Restore-SPEnterpriseSearchServiceApplicationIndex -SearchApplication $ssa -BackupFolder "\\sample\backup\spbr0000"
    Restore-SPEnterpriseSearchServiceApplicationIndex -SearchApplication $ssa -Handle $handle
  description: |-
    This example starts a restore of the search index in the default search service application from a backup located at \\\\sample\backup\spbr0000.
  summary: ""
- title: '------------------EXAMPLE 2------------------'
  code: |-
    $handle = Restore-SPEnterpriseSearchServiceApplicationIndex -SearchApplication $ssa -BackupFolder "\\sample\backup\spbr0000"
    Restore-SPEnterpriseSearchServiceApplicationIndex -SearchApplication "Search Service Application" -Handle $handle
  description: |-
    This example checks the status of the running job to restore of the search index in the search service application Search Service Application with the handle $handle .
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AllowMove
  description: |+
    Specifies a switch to move instead of copying files when restoring. 
    Moving may be faster than copying.


  defaultValue: None
  position: "4"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AllReplicas
  description: |+
    Specifies a switch to restore all replicas, not just the primary.

  defaultValue: None
  position: "3"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: BackupFolder
  isRequired: true
  description: |+
    Specifies the full file path of the backup files.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Handle
  isRequired: true
  description: |+
    A handle returned from an initial call using Parameter set 1.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Retries
  description: |+
    Specifies the number of times to retry if temporary failure occurs.

  defaultValue: None
  position: "5"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: RetryPauseSeconds
  description: |+
    Seconds to pause between retries if temporary failure occurs.

  defaultValue: None
  position: "6"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SearchServiceApplication" data-throw-if-not-resolved="False" />
  name: SearchApplication
  isRequired: true
  description: |+
    Specifies the search service application that contains the index files that should be restored.

  defaultValue: None
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.Restore-SPEnterpriseSearchServiceApplicationIndex
name: Restore-SPEnterpriseSearchServiceApplicationIndex
description: |-
  This cmdlet contains more than one parameter set.
  You may only use parameters from one parameter set and you may not combine parameters from different parameter sets.
  For more information about how to use parameter sets, see [Cmdlet parameter sets](https://learn.microsoft.com/powershell/scripting/developer/cmdlet/cmdlet-parameter-sets).

  This cmdlet will clear the complete search index for a specified search service application and replace it with the search index from the specified backup files.

  This cmdlet supports parameter sets.
  The first set of parameters is for Application Configuration Attach mode and the second set of parameters is for Search Application Attach mode.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.Office.Server.Search.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/restore-spenterprisesearchserviceapplicationindex
  applicable: SharePoint Server Subscription Edition
  title: Restore-SPEnterpriseSearchServiceApplicationIndex
  PlatyPS schema version: 2.0.0
