### YamlMime:PowershellCmdlet
summary: |-
  Changes the account used for the Identity of the specified application pool.
module: sharepoint-server
notes: ""
syntaxes:
- >-
  Set-SPServiceApplicationPool [-Identity] <SPIisWebServiceApplicationPoolPipeBind>
   [[-Account] <SPProcessAccountPipeBind>] [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-WhatIf]
   [<CommonParameters>]
examples:
- title: '------------------EXAMPLE-----------------------'
  code: |-
    Set-SPServiceApplicationPool  TestServiceWebApplicationPool -Account testdomain\testuser1
  description: |-
    This example changes the identity of the selected service application pool.

    For the Account parameter, the name of a managed account in the farm can be given.
    Use the `Get-SPManagedAccount` cmdlet to view the existing managed account in the farm.
    Also, a process account from the output of the `Get-SPProcessAccount` cmdlet can be used.
  summary: ""
parameters:
- type: <xref href="SPProcessAccountPipeBind" data-throw-if-not-resolved="False" />
  name: Account
  description: |+
    Specifies the credentials that will be the new Identity of the application pool.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPIisWebServiceApplicationPoolPipeBind" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Specifies the identity of the Web service application pool to configure.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.Set-SPServiceApplicationPool
name: Set-SPServiceApplicationPool
description: |-
  The `Set-SPServiceApplicationPool` cmdlet changes the account used for the Identity of the specified application pool.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/set-spserviceapplicationpool
  applicable: SharePoint Server Subscription Edition
  title: Set-SPServiceApplicationPool
  PlatyPS schema version: 2.0.0
