### YamlMime:PowershellCmdlet
summary: |-
  Sets the properties for how the OData service is configured for an instance of Project Web App.
module: sharepoint-server
notes: ""
syntaxes:
- >-
  Set-SPProjectOdataConfiguration [-AcceptCountRequests <Boolean>] [-AcceptProjectionRequests <Boolean>]
   [-AssignmentCollection <SPAssignmentCollection>] [-ClearEntityPageSizeOverrides] [-DefaultMaxPageSize <Int32>]
   [-EntitySetName <String>] [-MaxResultsPerCollection <Int32>] [-PageSizeOverride <Int32>]
   [-UseVerboseErrors <Boolean>] [<CommonParameters>]
examples:
- title: '----------------------EXAMPLE 1-----------------------'
  code: |-
    Set-SPProjectOdataConfiguration -ClearEntityPageSizeOverrides
  description: |-
    This example clears any page size overrides that have been set for any specific entities.
  summary: ""
- title: '----------------------EXAMPLE 2-----------------------'
  code: |-
    Set-SPProjectOdataConfiguration -AcceptProjectionRequests $true
  description: |-
    This example sets AcceptProjectionRequests to true.
  summary: ""
- title: '----------------------EXAMPLE 3-----------------------'
  code: |-
    Set-SPProjectOdataConfiguration -DefaultMaxPageSize 50
  description: |-
    This example sets the default maximum page size to 50 rows.
  summary: ""
- title: '----------------------EXAMPLE 4-----------------------'
  code: |-
    Set-SPProjectOdataConfiguration -EntitySetName Assignments -PageSizeOverride 100
  description: |-
    This example sets the page size override for the Assignments entity.
  summary: ""
parameters:
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AcceptCountRequests
  description: |+
    Sets whether requests with the $count path segment or the $inlinecount query options are accepted.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AcceptProjectionRequests
  description: |+
    Sets whether projection requests should be accepted. 
    Projection requests are made by using the $select query option.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: ClearEntityPageSizeOverrides
  description: |+
    Clears all page-size overrides that had been set for any entities.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: DefaultMaxPageSize
  description: |+
    Sets the default page size. 
    This is used for any entities that do not have an override set using the PageSizeOverride parameter.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: EntitySetName
  description: |+
    Specifies the entity name that is used to set a page size override with PageSizeOverride.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MaxResultsPerCollection
  description: |+
    Sets the integer value that indicates the maximum number of results per entity.
    This parameter cannot be used in conjunction with paging.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: PageSizeOverride
  description: |+
    Overrides the page size that is used for a specific entity.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: UseVerboseErrors
  description: |+
    Sets the service to use more verbose error messages (for example, stack trace).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
uid: sharepoint-server.Set-SPProjectOdataConfiguration
name: Set-SPProjectOdataConfiguration
description: |-
  The `Set-SPProjectOdataConfiguration` cmdlet sets the settings for how the OData service is configured for an instance of Project Web App.
  It allows the user to configure the settings for a list of parameters that specify paging, the enabling of various querying functionality, whether MaxResultsPerCollection has been enabled and whether verbose errors are enabled.
  Paging can be specified per entity.
  If no paging overrides exist for a given entity, the DefaultMaxPageSize parameter is used. 
  MaxResultsPerCollection cannot be used in conjunction with paging.

  For permissions and the most current information about Windows PowerShell for Project Server, see the online documentation at https://go.microsoft.com/fwlink/p/?LinkId=251833 (https://go.microsoft.com/fwlink/p/?LinkId=251833).
metadata:
  external help file: microsoft.office.project.server.stsadmcommandhandler.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/set-spprojectodataconfiguration
  Applicable: SharePoint Server Subscription Edition
  title: Set-SPProjectOdataConfiguration
  PlatyPS schema version: 2.0.0
