### YamlMime:PowershellCmdlet
summary: |-
  Sets SharePoint Store settings for an app.
module: sharepoint-server
notes: ""
inputs:
- name: <xref href="Microsoft.SharePoint.PowerShell.SPAssignmentCollection" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-SPAppStoreConfiguration
  href: Get-SPAppStoreConfiguration.yml
syntaxes:
- >-
  Set-SPAppStoreConfiguration [-Url <String>] [-AssignmentCollection <SPAssignmentCollection>] [-Confirm]
   [-WhatIf] -Enable <Boolean> [<CommonParameters>]
examples:
- title: '--------------------EXAMPLE 1---------------------'
  code: |-
    Set-SPAppStoreConfiguration -Url https://office.microsoft.com -Enable $true
  description: |-
    This example sets the URL to the Office.com server.
  summary: ""
- title: '--------------------EXAMPLE 2---------------------'
  code: |-
    Set-SPAppStoreConfiguration -Enable $false
  description: |-
    This example turns off the SharePoint Store.
  summary: ""
- title: '--------------------EXAMPLE 3---------------------'
  code: |-
    Set-SPAppStoreConfiguration -Enable $true
  description: |-
    This example turns on the SharePoint Store.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal. Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management. Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory. When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store. If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.


  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.


  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Enable
  isRequired: true
  description: |+
    Specifies whether the Office Store services lets third- party add-ins to be found or downloaded.

    This is intended for administrators to disable discovery and downloads of third-party add-ins on their SharePoint tenants and site collections.

    The valid values are True and False.

    The default value is False.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Url
  description: |+
    Specifies the URL of the app for which to set SharePoint Store settings.

    The SharePoint store value should not be changed unless instructed by a Microsoft representative.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.


  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.Set-SPAppStoreConfiguration
name: Set-SPAppStoreConfiguration
description: |-
  Use the Set-SPAppStoreConfiguration cmdlet to set SharePoint Store settings for a specified app.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at Windows PowerShell for SharePoint Server 2016, SharePoint Server 2019 reference [https://go.microsoft.com/fwlink/p/?LinkId=671715](https://go.microsoft.com/fwlink/p/?LinkId=671715).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/set-spappstoreconfiguration
  applicable: SharePoint Server Subscription Edition
  title: Set-SPAppStoreConfiguration
  PlatyPS schema version: 2.0.0
