### YamlMime:PowershellCmdlet
summary: |-
  Sets the settings for the Project Calculation Engine on Project Server.
module: sharepoint-server
notes: ""
syntaxes:
- >-
  Set-SPProjectPCSSettings [-ServiceApplication <PsiServiceApplicationPipeBind>]
   [-AssignmentCollection <SPAssignmentCollection>] [-CachePersistence <Int32>] [-EditingSessionTimeout <Int32>]
   [-MaximumIdleWorkersCount <Int32>] [-MaximumProjectSize <Int32>] [-MaximumSessionsPerUser <Int32>]
   [-MaximumWorkersCount <Int32>] [-MinimumMemoryRequired <Int32>] [-RequestTimeLimits <Int32>]
   [-NetTcpPort <Int32>] [<CommonParameters>]
examples:
- title: '----------------------EXAMPLE-----------------------'
  code: |-
    Set-SPProjectPCSSettings -sa "Project Service Application" -MaximumSessionsPerUser 500
  description: |-
    This example sets 500 as the maximum allowed Project Calculation Engine sessions that a user can open on the "Project Service Application" service application.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: CachePersistence
  description: |+
    The maximum length of time before the Project Calculation Engine can begin to remove temporary cache files of projects opened on the Project Server service application.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: EditingSessionTimeout
  description: |+
    The maximum length of time that a user can be idle in a Project Calculation Engine session before a timeout occurs.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MaximumIdleWorkersCount
  description: |+
    The maximum number of idle Project Calculation Engine sessions available at a given time.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MaximumProjectSize
  description: |+
    The maximum size of a project that can be opened by the Project Calculation Engine.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MaximumSessionsPerUser
  description: |+
    The maximum number of sessions that a user is allowed to open.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MaximumWorkersCount
  description: |+
    The maximum number of Project Calculation Engine sessions that can be created.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MinimumMemoryRequired
  description: |+
    The minimum memory required before launching a new Project Calculation Engine session.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: NetTcpPort
  description: |+
    The TCP port to use with the PCS service.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: RequestTimeLimits
  description: |+
    The maximum allowable time for a request to the Project Calculation Engine to complete before the Project Calculation Engine session is terminated.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="PsiServiceApplicationPipeBind" data-throw-if-not-resolved="False" />
  name: ServiceApplication
  description: |+
    The Project Server service application for which the settings are to be read.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: sa
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
uid: sharepoint-server.Set-SPProjectPCSSettings
name: Set-SPProjectPCSSettings
description: |-
  The `Set-SPProjectPCSSettings` cmdlet lets you configure the different settings that govern the operations of the Project Calculation Engine on Project Server.
  The settings are per service application, which is identified by the Service Application parameter provided to this cmdlet.
  The settings have maximum and minimum values that are enforced by Project Server.

  For permissions and the most current information about Windows PowerShell for Project Server, see the online documentation at https://go.microsoft.com/fwlink/p/?LinkId=251833 (https://go.microsoft.com/fwlink/p/?LinkId=251833).
metadata:
  external help file: microsoft.office.project.server.stsadmcommandhandler.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/set-spprojectpcssettings
  Applicable: SharePoint Server Subscription Edition
  title: Set-SPProjectPCSSettings
  PlatyPS schema version: 2.0.0
