### YamlMime:PowershellCmdlet
summary: |-
  Sets the configuration properties of a site subscription.
module: sharepoint-server
notes: ""
syntaxes:
- >-
  Set-SPSiteSubscriptionConfig [-Identity] <SPSiteSubscriptionPipeBind>
   [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-PassThru] [-UserAccountDirectoryPath <String>]
   [-WhatIf] [-FeaturePack <SPSiteSubscriptionFeaturePackPipeBind>] [<CommonParameters>]
examples:
- title: '--------------------EXAMPLE---------------------'
  code: |-
    Set-SPSiteSubscriptionConfig https://contoso.com -FeaturePack 12345678-90ab-cdef-1234-567890abcdef
  description: |-
    This example sets the Feature set of the entire site subscription that contains https://contoso.com with a Feature pack GUID.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPSiteSubscriptionFeaturePackPipeBind" data-throw-if-not-resolved="False" />
  name: FeaturePack
  description: |+
    {{Fill FeaturePack Description}}

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPSiteSubscriptionPipeBind" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Specifies the site subscription configuration to update.

    The type must be a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; an SPSite (object or URL) of a site collection that is a member of the site subscription; or an instance of a valid SiteSubscription object.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Specifies the output object can be passed through the pipeline.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: UserAccountDirectoryPath
  description: |+
    Sets the site user account directory path to a specific organizational unit (OU) that is in the same domain as the site subscription.

    The type must be a name of a distinguished OU; for example, OU=Contoso1, DC=OSGCorp,DC=local.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.Set-SPSiteSubscriptionConfig
name: Set-SPSiteSubscriptionConfig
description: |-
  The `Set-SPSiteSubscriptionConfig` cmdlet sets the configuration properties of a site subscription.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/set-spsitesubscriptionconfig
  applicable: SharePoint Server Subscription Edition
  title: Set-SPSiteSubscriptionConfig
  PlatyPS schema version: 2.0.0
