### YamlMime:PowershellCmdlet
summary: |-
  Sets the identifier of the farm or tenant used by the Office Marketplace to issue App licenses.
module: sharepoint-server
notes: ""
syntaxes:
- >-
  Set-SPAppManagementDeploymentId -AppManagementServiceApplication <AppManagementServiceApplication>
   -DeploymentId <Guid> [-AssignmentCollection <SPAssignmentCollection>] [-Confirm]
   [-Identity <SPSiteSubscriptionPipeBind>] [-WhatIf] [<CommonParameters>]
examples:
- title: '-----------EXAMPLE 1----------'
  code: |-
    $sa = Get-SPServiceApplication | where {$_.TypeName -eq "App Management Service Application"}
    Set-SPAppManagementDeploymentId -DeploymentId 3102B7C3-1866-48EE-91CB-84E20AD24BF2 -AppManagementServiceApplication $sa
  description: |-
    This example sets the deployment identifier of the current farm to 3102B7C3-1866-48EE-91CB-84E20AD24BF2.
  summary: ""
- title: '-----------EXAMPLE 2----------'
  code: |-
    $sa = Get-SPServiceApplication | where {$_.TypeName -eq "App Management Service Application"}
    Get-SPSiteSubscription | where{$_.Id -eq "88f16a50-0530-4f3f-b749-24ef0b30d685"} | Set-SPAppManagementDeploymentId -DeploymentId 3102B7C3-1866-48EE-91CB-84E20AD24BF2 -AppManagementServiceApplication $sa
  description: |-
    This example sets the deployment identifier of the tenant with the site subscription identifier 88f16a50-0530-4f3f-b749-24ef0b30d685 to 3102B7C3-1866-48EE-91CB-84E20AD24BF2.
  summary: ""
parameters:
- type: <xref href="AppManagementServiceApplication" data-throw-if-not-resolved="False" />
  name: AppManagementServiceApplication
  isRequired: true
  description: |+
    Specifies the app management service application object that is running on the farm.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: DeploymentId
  isRequired: true
  description: |+
    Specifies the deployment identifier value for the tenant.
    This parameter works in conjunction with the value that is defined with Identity parameter.
    If Identity parameter is omitted, then it is assumed that this deployment identifier value belongs to the farm.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPSiteSubscriptionPipeBind" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Identifies the site subscription object representing the tenant to which the DeploymentId parameter is to be assigned.
    If the Identity parameter is omitted, it is assumed that the deployment identifier belongs to the farm.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: Subscription
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.Set-SPAppManagementDeploymentId
name: Set-SPAppManagementDeploymentId
description: |-
  Use the `Set-SPAppManagementDeploymentId` cmdlet to set the identifier of the farm or tenant used by the Office Marketplace to issue App Licenses.
  To ensure you do not lose rights to the use of all Apps you have purchased on the Marketplace, do not change the deployment id unless directed by Microsoft documentation or support.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/set-spappmanagementdeploymentid
  applicable: SharePoint Server Subscription Edition
  title: Set-SPAppManagementDeploymentId
  PlatyPS schema version: 2.0.0
