### YamlMime:PowershellCmdlet
summary: |-
  Sets the application credential key on the local server.
module: sharepoint-server
links:
- text: Remove-SPApplicationCredentialKey
  href: Remove-SPApplicationCredentialKey.yml
syntaxes:
- >-
  Set-SPApplicationCredentialKey [-Password] <SecureString> [-AssignmentCollection <SPAssignmentCollection>]
   [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '------------EXAMPLE -----------'
  code: |-
    $key = ConvertTo-SecureString -String "New Password" -AsPlainText -Force
    Set-SPApplicationCredentialKey -Password $key
  description: |-
    This example sets the application credential key on the local server to "New Password".
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SecureString" data-throw-if-not-resolved="False" />
  name: Password
  isRequired: true
  description: |+
    Specifies the application credential key.
    Avoid reusing the farm passphrase or service account passwords for the application credential key.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
uid: sharepoint-server.Set-SPApplicationCredentialKey
name: Set-SPApplicationCredentialKey
description: |-
  Use the **Set-SPApplicationCredentialKey** cmdlet to set the application credential key on the local server, which is used by certain features to encrypt and decrypt passwords.

  The application credential key must be identical on each server in the farm where it is set.
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/set-spapplicationcredentialkey
  Applicable: SharePoint Server Subscription Edition
  title: Set-SPApplicationCredentialKey
  PlatyPS schema version: 2.0.0
