### YamlMime:PowershellCmdlet
summary: |-
  Updates the SPObjectSecurity object for a service application.
module: sharepoint-server
notes: ""
syntaxes:
- >-
  Set-SPServiceApplicationSecurity [-Identity] <SPServiceApplicationPipeBind>
   [-ObjectSecurity] <SPObjectSecurity> [-Admin] [-AssignmentCollection <SPAssignmentCollection>]
   [<CommonParameters>]
examples:
- title: '--------------------EXAMPLE---------------------'
  code: |-
    $sa = Get-SPServiceApplication -Identity <ID>
    $security = Get-SPServiceApplicationSecurity $sa -Admin
    $principal = New-SPClaimsPrincipal contoso\johndoe -IdentityType WindowsSamAccountName
    Grant-SPObjectSecurity $security $principal "Full Control"
    Set-SPServiceApplicationSecurity $sa -Admin $security
  description: |-
    This example retrieves the SPObjectSecurity object corresponding to the administrator ACL on a service application and adds a new user principal to that ACL.
    The new user is an administrator for the service application $serviceApp.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Admin
  description: |+
    Updates the access control list (ACL) that contains the administrators list of the service application.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPServiceApplicationPipeBind" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Specifies the service application that contains the SPObjectSecurity object to update.

    The type must be a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; a valid name of a service application (for example, ServiceApp1); or an instance of a valid SPServiceApplication object.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPObjectSecurity" data-throw-if-not-resolved="False" />
  name: ObjectSecurity
  isRequired: true
  description: |+
    Specifies the SPObjectSecurity object to update.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.Set-SPServiceApplicationSecurity
name: Set-SPServiceApplicationSecurity
description: |-
  The `Set-SPServiceApplicationSecurity` cmdlet updates a security object for the specified service application.
  Use this cmdlet with the `Grant-SPObjectSecurity` and `Get-SPServiceApplicationSecurity` cmdlets to manage security for a service application.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/set-spserviceapplicationsecurity
  applicable: SharePoint Server Subscription Edition
  title: Set-SPServiceApplicationSecurity
  PlatyPS schema version: 2.0.0
