### YamlMime:PowershellCmdlet
summary: |-
  Sets properties of a User Profile Service application.
module: sharepoint-server
notes: ""
syntaxes:
- >-
  Set-SPProfileServiceApplication [-Identity] <SPServiceApplicationPipeBind>
   [-ApplicationPool <SPIisWebServiceApplicationPoolPipeBind>] [-AssignmentCollection <SPAssignmentCollection>]
   [-Confirm] [-GetNonImportedObjects <Boolean>] [-MySiteHostLocation <SPSitePipeBind>]
   [-ProfileDBCredentials <PSCredential>] [-ProfileSyncDBCredentials <PSCredential>]
   [-ProfileSyncDBFailoverServer <String>] [-PurgeNonImportedObjects <Boolean>]
   [-SocialDBCredentials <PSCredential>] [-SocialDBFailoverServer <String>] [-Name <String>]
   [-UseOnlyPreferredDomainControllers <Boolean>] [-WhatIf] [-ProfileDBFailoverServer <String>]
   [<CommonParameters>]
- >-
  Set-SPProfileServiceApplication [-Identity] <SPServiceApplicationPipeBind>
   [-ApplicationPool <SPIisWebServiceApplicationPoolPipeBind>] [-AssignmentCollection <SPAssignmentCollection>]
   [-Confirm] [-GetNonImportedObjects <Boolean>] -MySiteHostLocation <SPSitePipeBind>
   [-MySiteManagedPath <SPPrefixPipeBind>] [-ProfileDBCredentials <PSCredential>]
   [-ProfileSyncDBCredentials <PSCredential>] [-ProfileSyncDBFailoverServer <String>]
   [-PurgeNonImportedObjects <Boolean>] [-SiteNamingConflictResolution <String>]
   [-SocialDBCredentials <PSCredential>] [-SocialDBFailoverServer <String>] [-Name <String>]
   [-UseOnlyPreferredDomainControllers <Boolean>] [-WhatIf] [-ProfileDBFailoverServer <String>]
   [<CommonParameters>]
examples:
- title: '---------------EXAMPLE---------------------'
  code: |-
    $sa = Get-SPServiceApplication | ?{$_.TypeName -eq 'User Profile Service Application'}
    Set-SPProfileServiceApplication -Identity $sa -PurgeNonImportedObjects:$true
  description: |-
    This example purges objects from the Profile database which are not in scope of the User Profile import.
  summary: ""
parameters:
- type: <xref href="SPIisWebServiceApplicationPoolPipeBind" data-throw-if-not-resolved="False" />
  name: ApplicationPool
  description: |+
    Specifies the existing IIS application pool in which to run the Web service for the service application.

    The type must be a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; a valid name of an application pool (for example, AppPoolName1); or an instance of a valid IISWebServiceApplicationPool object.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: GetNonImportedObjects
  description: |+
    Specifies whether to inform the users that did not come from the import pipeline and will be marked for deletion.
    The list of users marked for deletion is displayed to the console window.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPServiceApplicationPipeBind" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Specifies the User Profile Service application to update.

    The type must be a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; a valid name of a subscription settings service application (for example, SubscriptionSettingsApp1); or an instance of a valid SPServiceApplication object.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPSitePipeBind" data-throw-if-not-resolved="False" />
  name: MySiteHostLocation
  isRequired: true
  description: |+
    Specifies the site collection where the My Site will be provisioned.

    The type must be a valid URL, in the form https://server_name; a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; a valid name of a site subscription (for example, SiteSubscription1); or an instance of a valid SiteSubscription object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPPrefixPipeBind" data-throw-if-not-resolved="False" />
  name: MySiteManagedPath
  description: |+
    Specifies the managed path location of personal sites.

    The type must be a valid URL, in the form https://server_name.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the display name for the new User Profile Service application.
    The name that you use must be a unique name of a User Profile Service application in this farm.
    The name can be a maximum of 128 characters.

    The type must be a valid name of a User Profile Service application; for example, UserProfileSvcApp1.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
  name: ProfileDBCredentials
  description: |+
    Specifies the set of security credentials, such as a user name and a password, that is used to connect to the User Profile database that this cmdlet creates.

    The type must be a valid PSCredential object.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ProfileDBFailoverServer
  description: |+
    Specifies the name of the failover SQL server for Profile database. It is used to build the connection string for the Profile database.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
  name: ProfileSyncDBCredentials
  description: |+
    Specifies the set of security credentials, such as a user name and a password, that will be used to connect to the Profile Sync database that is specified in the ProfileSyncDBName parameter.

    The type must be a valid PSCredential object.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ProfileSyncDBFailoverServer
  description: |+
    Specifies the name of the failover SQL server for Profile database.
    It is used to build the connection string for the Profile database.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: PurgeNonImportedObjects
  description: |+
    Specifies whether to mark the non-imported users in the profile store for deletion and then inform the users that did not come from the import pipeline which will be marked for deletion.
    The list of users marked for deletion is displayed on the console window

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SiteNamingConflictResolution
  description: |+
    Specifies the format to use to name personal sites.

    Use one of the following integer values:

    1--Personal site collections are to be based on user names without any conflict resolution.
    For example, https://portal_site/location/username/

    2-- Personal site collections are to be based on user names with conflict resolution by using domain names.
    For example, .../username/ or .../domain_username/

    3   Personal site collections are to be named by using domain and user name always, to avoid any conflicts.
    For example, https://portal_site/location/domain_username/

    The default value is 1 (do not resolve conflicts).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
  name: SocialDBCredentials
  description: |+
    The set of security credentials, including a user name and a password, that is used to connect to the Social database that this cmdlet creates.

    The type must be a valid PSCredential object.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SocialDBFailoverServer
  description: |+
    Specifies the name of the failover SQL server for Social database.
    It is used to build the connection string for the Social database.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: UseOnlyPreferredDomainControllers
  description: |+
    Restricts profile synchronization communication to a specific domain controller.

    The valid values are $true or $false.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.Set-SPProfileServiceApplication
name: Set-SPProfileServiceApplication
description: |-
  This cmdlet contains more than one parameter set.
  You may only use parameters from one parameter set and you may not combine parameters from different parameter sets.
  For more information about how to use parameter sets, see [Cmdlet parameter sets](https://learn.microsoft.com/powershell/scripting/developer/cmdlet/cmdlet-parameter-sets).

  The Set-SPProfileServiceApplication cmdlet sets properties of a User Profile Service application.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.Office.Server.UserProfiles.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/set-spprofileserviceapplication
  applicable: SharePoint Server Subscription Edition
  title: Set-SPProfileServiceApplication
  PlatyPS schema version: 2.0.0
