### YamlMime:PowershellCmdlet
summary: |-
  Configures one or more common settings for all web services.
module: sharepoint-server
notes: ""
syntaxes:
- >-
  Set-SPServiceHostConfig [-Identity] <SPIisWebServiceSettings> [-HttpPort <Int32>] [-HttpsPort <Int32>]
   [-NetTcpPort <Int32>] [-ImportSslCertificate <X509Certificate2>] [-AllowLegacyEncryption] [-NoWait]
   [-AssignmentCollection <SPAssignmentCollection>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-SPServiceHostConfig [-Identity] <SPIisWebServiceSettings> [-HttpPort <Int32>] [-HttpsPort <Int32>]
   [-NetTcpPort <Int32>] -SslCertificateThumbprint <String> [-SslCertificateStoreName <String>]
   [-AllowLegacyEncryption] [-NoWait] [-AssignmentCollection <SPAssignmentCollection>] [-WhatIf] [-Confirm]
   [<CommonParameters>]
- >-
  Set-SPServiceHostConfig [-Identity] <SPIisWebServiceSettings> -SslCertificateThumbprint <String>
   [-SslCertificateStoreName <String>] [-RunInProcess] [-AssignmentCollection <SPAssignmentCollection>] [-WhatIf]
   [-Confirm] [<CommonParameters>]
examples:
- title: '------------------EXAMPLE-----------------------'
  code: |-
    Set-SPServiceHostConfig -Port 12345
  description: |-
    This example sets the HTTP port for the web services.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AllowLegacyEncryption
  description: |+
    Specifies that older SSL and TLS protocol versions and cipher suites are allowed to be used with this IIS website.
    Legacy encryption is weaker than modern encryption and is not recommended.

    This feature requires Windows Server 2022 or higher.
    This feature is not available when SharePoint is deployed with earlier versions of Windows Server.

    This parameter is only valid when used with the SecureSocketsLayer parameter.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: \`get-help about_commonparameters\`

  defaultValue: "False"
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: HttpPort
  description: |+
    Specifies the new port for the web service.

  defaultValue: None
  position: Named
  aliases: Port
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: HttpsPort
  description: |+
    Specifies the new secure port for the web service.

  defaultValue: None
  position: Named
  aliases: SecurePort
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPIisWebServiceSettings" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Specifies the identity of the web service application to configure.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="X509Certificate2" data-throw-if-not-resolved="False" />
  name: ImportSslCertificate
  description: |+
    Specifies the SSL Certificate to use for secure protocols.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: NetTcpPort
  description: |+
    Sets the TCP port for the web service.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: NoWait
  description: |+
    For more information, see TechNet.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: RunInProcess
  isRequired: true
  description: |+
    Specifies to update the web service application configuration using the current process instead of a SharePoint Timer job.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SslCertificateStoreName
  description: |+
    Specifies the name of the certificate store containing the SSL certificate to retrieve for secure protocols.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SslCertificateThumbprint
  isRequired: true
  description: |+
    Specifies the thumbprint of the SSL certificate to retrieve for secure protocols.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.Set-SPServiceHostConfig
name: Set-SPServiceHostConfig
description: |-
  This cmdlet contains more than one parameter set.
  You may only use parameters from one parameter set and you may not combine parameters from different parameter sets.
  For more information about how to use parameter sets, see [Cmdlet parameter sets](https://learn.microsoft.com/powershell/scripting/developer/cmdlet/cmdlet-parameter-sets).

  The `Set- SPServiceHostConfig` cmdlet configures one or more common settings for all web services.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/set-spservicehostconfig
  applicable: SharePoint Server Subscription Edition
  title: Set-SPServiceHostConfig
  PlatyPS schema version: 2.0.0
