### YamlMime:PowershellCmdlet
summary: |-
  Sets properties of a Secure Store application.
module: sharepoint-server
notes: ""
syntaxes:
- >-
  Set-SPSecureStoreApplication -Identity <SPSecureStoreApplication> [-Administrator <SPClaim[]>]
   [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-CredentialsOwnerGroup <SPClaim[]>]
   [-Fields <TargetApplicationField[]>] [-TargetApplication <TargetApplication>] [-TicketRedeemer <SPClaim[]>]
   [-WhatIf] [<CommonParameters>]
examples:
- title: '------------------EXAMPLE------------------'
  code: |-
    $targetApp.FriendlyName = "Updated Contoso Target App"
    Set-SPSecureStoreApplication -Identity $application -TargetApplication $targetApp
  description: |-
    This example sets a new display name Updated Contoso Target App for the target application.
  summary: ""
parameters:
- type: <xref href="SPClaim" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Administrator
  description: |+
    Specifies the administrator of the Secure Store application.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPClaim" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CredentialsOwnerGroup
  description: |+
    Specifies the claims object for the groups that own the group credentials.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="TargetApplicationField" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Fields
  description: |+
    Specifies the field information for the application.
    The default fields are username and password.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPSecureStoreApplication" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Specifies the Secure Store application to update.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="TargetApplication" data-throw-if-not-resolved="False" />
  name: TargetApplication
  description: |+
    Specifies the target application.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPClaim" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: TicketRedeemer
  description: |+
    Specifies the ticket redeemer claim value.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.Set-SPSecureStoreApplication
name: Set-SPSecureStoreApplication
description: |-
  The `Set-SPSecureStoreApplication` cmdlet sets properties of a Secure Store application.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.SSOUpgrade-help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/set-spsecurestoreapplication
  applicable: SharePoint Server Subscription Edition
  title: Set-SPSecureStoreApplication
  PlatyPS schema version: 2.0.0
