### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet configures settings for data retrieval services.
module: sharepoint-server
notes: ""
syntaxes:
- >-
  Update-SPDataRetrievalServiceConfig [-WebApplication] <SPWebApplicationPipeBind> [-Inherit] [-Enable <Boolean>]
   [-LimitResponseSize <Int32>] [-EnableUpdateSupport <Boolean>] [-DataSourceTimeout <Int32>]
   [-EnableDataSourceControls <Boolean>] [-AssignmentCollection <SPAssignmentCollection>] [-WhatIf] [-Confirm]
   [<CommonParameters>]
- >-
  Update-SPDataRetrievalServiceConfig [-Farm] [-Enable <Boolean>] [-LimitResponseSize <Int32>]
   [-EnableUpdateSupport <Boolean>] [-DataSourceTimeout <Int32>] [-EnableDataSourceControls <Boolean>]
   [-AssignmentCollection <SPAssignmentCollection>] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------EXAMPLE 1-------------'
  code: |-
    Update-SPDataRetrievalServiceConfig -Farm -Enable $false
  description: |-
    This example turns off the data retrieval service for the farm.
  summary: ""
- title: '-------------EXAMPLE 2-------------'
  code: |-
    Update-SPDataRetrievalServiceConfig -WebApplication http://MyOfficeApp1 -Inherit
  description: |-
    This example enables the Web application, MyOfficeApp1, to inherit the global settings.
  summary: ""
- title: '-------------EXAMPLE 3-------------'
  code: |-
    Update-SPDataRetrievalServiceConfig -WebApplication http://MyOfficeApp1 -Enable $false
  description: |-
    This example turns off the data retrieval service for the Web application, MyOfficeApp1.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: DataSourceTimeout
  description: |+
    Set the response timeout in second.

    This setting applies to the following data retrieval services:

    OLEDB/

    SOAP Passthrough

    XML-URL

    SoapDataSource

    XmlUrlDataSource

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Enable
  description: |+
    @{Text=}

  defaultValue: "True"
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableDataSourceControls
  description: |+
    Enable or disable the set of data source controls on this server.

    This setting applies to the following data source controls:

    SPXmlDataSource

    XmlUrlDataSource

    SoapDataSource

    AggregateDataSource

  defaultValue: "True"
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableUpdateSupport
  description: |+
    Enable or disable the support for update queries.

    This setting applies to the following data retrieval services:

    OLEDB

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Farm
  isRequired: true
  description: |+
    Apply the setting to the farm, and to all the SharePoint Web applications inherit the config.

  defaultValue: None
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Inherit
  description: |+
    Set whether inherit the global setting of the farm.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: LimitResponseSize
  description: |+
    The maximum size of the SOAP response that the data source returns to the data retrieval service, specified by kilobytes(KB).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SPWebApplicationPipeBind" data-throw-if-not-resolved="False" />
  name: WebApplication
  isRequired: true
  description: |+
    Apply the setting to the specified SharePoint Web application.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.Update-SPDataRetrievalServiceConfig
name: Update-SPDataRetrievalServiceConfig
description: |-
  This cmdlet contains more than one parameter set.
  You may only use parameters from one parameter set, and you may not combine parameters from different parameter sets.
  For more information about how to use parameter sets, see Cmdlet Parameter Sets (https://go.microsoft.com/fwlink/?LinkID=187810).

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at Windows PowerShell for SharePoint Server 2016 reference (https://go.microsoft.com/fwlink/p/?LinkId=671715).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-Help.xml
  module name: SharePointServer
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/update-spdataretrievalserviceconfig
  applicable: SharePoint Server Subscription Edition
  title: Update-SPDataRetrievalServiceConfig
  PlatyPS schema version: 2.0.0
