### YamlMime:PowershellCmdlet
summary: |-
  Takes a backup of the search index to a specified backup location.
module: SharePointServer
notes: ""
syntaxes:
- >-
  Backup-SPEnterpriseSearchServiceApplicationIndex [-Phase] <Int32>
   [-SearchApplication] <SearchServiceApplication> [-BackupFolder] <String> [-BackupHandleFile] <String>
   [[-Retries] <Int32>] [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-WhatIf] [-PeerToPeer]
   [-SpecifiedBackupHandle <String>] [<CommonParameters>]
- >-
  Backup-SPEnterpriseSearchServiceApplicationIndex [-SearchApplication] <SearchServiceApplication>
   [-BackupHandleFile] <String> [[-Retries] <Int32>] [-AssignmentCollection <SPAssignmentCollection>] [-Confirm]
   [-WhatIf] [-Abort] [-PeerToPeer] [-SpecifiedBackupHandle <String>] [<CommonParameters>]
examples:
- title: '------------------EXAMPLE 1------------------'
  code: |-
    $ssa = Get-SPEnterpriseSearchServiceApplication
    Backup-SPEnterpriseSearchServiceApplicationIndex -Phase 1 -SearchApplication $ssa -BackupFolder "\\backuphost\backupfolder" -BackupHandleFile "\\backuphost\backupfolder\backuphandle.txt" -Retries 3
  description: |-
    This example starts a Phase 1 backup of the search index for the default search application, and stores the backup at the location \\\\backuphost\backupfolder. 
    The cmdlet stores a handle file backuphandle.txt that is used by the second phase cmdlet.
  summary: ""
- title: '------------------EXAMPLE 2------------------'
  code: |-
    $ssa = Get-SPEnterpriseSearchServiceApplication
    Backup-SPEnterpriseSearchServiceApplicationIndex -Phase 1 $ssa -BackupFolder "\\backuphost\backupfolder" -BackupHandleFile "\\backuphost\backupfolder\backuphandle.txt" -Retries 3
  description: |-
    This example checks the backup status and progress by re-running the cmdlet for Phase 1.
  summary: ""
- title: '------------------EXAMPLE 3------------------'
  code: |-
    $ssa = Get-SPEnterpriseSearchServiceApplication
    Backup-SPEnterpriseSearchServiceApplicationIndex -Phase 2 -SearchApplication $ssa -BackupFolder "\\backuphost\backupfolder" -BackupHandleFile "\\backuphost\backupfolder\backuphandle.txt" -Retries 3
  description: |-
    This example starts the Phase 2 of the search index backup by using the same backup location and backup handle file as used for Phase 1. 
    The Search Service Application must be paused before the second phase can be started.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Abort
  isRequired: true
  description: |+
    {{Fill Abort Description}}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: BackupFolder
  isRequired: true
  description: |+
    Full UNC path of the backup files should be written.

  defaultValue: None
  position: "3"
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: BackupHandleFile
  isRequired: true
  description: |+
    Specifies a file handle for an ongoing backup job.

  defaultValue: None
  position: "4"
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PeerToPeer
  description: |+
    {{Fill PeerToPeer Description}}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Phase
  isRequired: true
  description: |+
    Specifies the phase of the backup job.

  defaultValue: None
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Retries
  description: |+
    Number of times to retry if temporary failure occurs.

  defaultValue: None
  position: "5"
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SearchServiceApplication" data-throw-if-not-resolved="False" />
  name: SearchApplication
  isRequired: true
  description: |+
    Name of the search service application to be backed up

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SpecifiedBackupHandle
  description: |+
    {{Fill SpecifiedBackupHandle Description}}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2013
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.Backup-SPEnterpriseSearchServiceApplicationIndex
name: Backup-SPEnterpriseSearchServiceApplicationIndex
description: |-
  This cmdlet will take a backup of the search index to a specified backup location. 
  The cmdlet has to be run in two phases. 
  Phase one will take a backup of what is present in the index at the time that the backup cmdlet is run. 
  Phase two will take a differential backup of what was added to the index after you started the first phase index backup.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.Office.Server.Search.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/backup-spenterprisesearchserviceapplicationindex
  applicable: SharePoint Server 2013, SharePoint Server 2016, SharePoint Server 2019
  title: Backup-SPEnterpriseSearchServiceApplicationIndex
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
