### YamlMime:PowershellCmdlet
summary: |-
  Returns the settings for how the OData service is configured for an instance of Project Web App.
module: SharePointServer
notes: ""
syntaxes:
- Get-SPProjectOdataConfiguration [-AssignmentCollection <SPAssignmentCollection>] [<CommonParameters>]
examples:
- title: '----------------------EXAMPLE 1-----------------------'
  code: |-
    Get-SPProjectOdataConfiguration
  description: |-
    This example returns the OData configuration for the instance of Project Web App.
  summary: ""
- title: '----------------------EXAMPLE 2-----------------------'
  code: |-
    C:\PS>(Get-SPProjectOdataConfiguration).EntitySetsWithMaxPAgeSizeOverride
  description: |-
    This example returns the list of entities that have the MaxPageSizeOverride option configured.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Project Server 2013
  - Project Server 2016
  - Project Server 2019
  parameterValueGroup: ""
applicable:
- Project Server 2013
- Project Server 2016
- Project Server 2019
uid: SharePointServer.Get-SPProjectOdataConfiguration
name: Get-SPProjectOdataConfiguration
description: |-
  The Get-SPProjectOdataConfiguration cmdlet returns the settings for how the OData service is configured for an instance of Project Web App. 
  It returns the current settings for a list of parameters that specify paging, the enabling of various querying functionality, whether MaxResultsPerCollection has been enabled, and whether verbose errors are enabled.
  The cmdlet can also be used to return an itemized list of entities that have an override specified for their maximum page size.

  For permissions and the most current information about Windows PowerShell for Project Server, see the online documentation at https://go.microsoft.com/fwlink/p/?LinkId=251833 (https://go.microsoft.com/fwlink/p/?LinkId=251833).
metadata:
  external help file: microsoft.office.project.server.stsadmcommandhandler.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/get-spprojectodataconfiguration
  applicable: Project Server 2013, Project Server 2016, Project Server 2019
  title: Get-SPProjectOdataConfiguration
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
