### YamlMime:PowershellCmdlet
summary: |-
  Returns properties of a SharePoint Store app.
module: SharePointServer
notes: ""
inputs:
- name: <xref href="Microsoft.SharePoint.PowerShell.SPAssignmentCollection" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Get-SPAppStoreWebServiceConfiguration [-AssignmentCollection <SPAssignmentCollection>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-SPAppStoreWebServiceConfiguration
  description: |-
    This example returns the product type and version for a SharePoint Store app.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal. Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management. Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory. When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store. If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.Get-SPAppStoreWebServiceConfiguration
name: Get-SPAppStoreWebServiceConfiguration
description: |-
  Use the `Get-SPAppStoreWebServiceConfiguration` cmdlet to return property settings or SharePoint Store apps.

  This cmdlet is not intended for the IT Pro audience.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at Windows PowerShell for SharePoint Server 2016, SharePoint Server 2019 reference [https://go.microsoft.com/fwlink/p/?LinkId=671715](https://go.microsoft.com/fwlink/p/?LinkId=671715).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/get-spappstorewebserviceconfiguration
  applicable: SharePoint Server 2016, SharePoint Server 2019
  title: Get-SPAppStoreWebServiceConfiguration
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
