### YamlMime:PowershellCmdlet
summary: |-
  Returns an Access Services application or a collection of Access Services applications.
module: SharePointServer
notes: ""
syntaxes:
- >-
  Get-SPAccessServiceApplication [[-Identity] <SPAccessServiceApplicationPipeBind>]
   [-AssignmentCollection <SPAssignmentCollection>] [<CommonParameters>]
examples:
- title: '------------EXAMPLE 1----------------'
  code: |-
    Get-SPAccessServiceApplication -identity "MyAccessService"
  description: |-
    This example displays an Access Services application named MyAccessService.
  summary: ""
- title: '------------EXAMPLE 2----------------'
  code: |-
    Get-SPAccessServiceApplication | where {$_.recordsintablemax -gt 10000}
  description: |-
    This example displays every Access Services application that run in the farm, which allows more than 10,000 records in a table.
  summary: ""
- title: '------------EXAMPLE 3----------------'
  code: |-
    Get-SPAccessServiceApplication
  description: |-
    This example displays every Access Services application in the farm.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPAccessServiceApplicationPipeBind" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Specifies the Access Services  application to get.

    The type must be a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; or an instance of a valid SPAccessServiceApplication object.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2010
- SharePoint Server 2013
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.Get-SPAccessServiceApplication
name: Get-SPAccessServiceApplication
description: |-
  The Get-SPAccessServiceApplication cmdlet retrieves an Access Services application.
  If an identity is not specified, the cmdlet returns the collection of Access Services applications that are in the farm.
  The properties returned from this cmdlet are read-only.
  If changes need to be made, use the Set-SPAccessServiceApplication cmdlet.
  These changes affect all computers in the farm in which this Access Services application runs.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: microsoft.office.access.services.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/get-spaccessserviceapplication
  applicable: SharePoint Server 2010, SharePoint Server 2013, SharePoint Server 2016, SharePoint Server 2019
  title: Get-SPAccessServiceApplication
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
