### YamlMime:PowershellCmdlet
summary: |-
  Returns the search service application proxy.
module: SharePointServer
notes: ""
syntaxes:
- >-
  Get-SPEnterpriseSearchServiceApplicationProxy [[-Identity] <SearchServiceApplicationProxyPipeBind>]
   [-AssignmentCollection <SPAssignmentCollection>] [<CommonParameters>]
examples:
- title: '------------------EXAMPLE------------------'
  code: |-
    $proxy = Get-SPEnterpriseSearchServiceApplicationProxy -Identity 'Search Service Application Proxy'
  description: |-
    This example obtains a reference to a search service application proxy with the name 'Search Service Application Proxy'.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal. Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management. Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory. When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store. If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SearchServiceApplicationProxyPipeBind" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Specifies the search service application proxy to retrieve.

    The type must be a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; a valid name of a search service application proxy (for example, SearchServiceAppProxy1); or an instance of a valid SearchServiceApplicationProxy object.

  defaultValue: None
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2010
- SharePoint Server 2013
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.Get-SPEnterpriseSearchServiceApplicationProxy
name: Get-SPEnterpriseSearchServiceApplicationProxy
description: |-
  This cmdlet reads the SearchServiceApplicationProxy object when the search service application proxy is created updated or deleted.
  If the Identity parameter is not specified, this cmdlet returns the search service application proxy collection for the farm.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.Office.Server.Search.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/get-spenterprisesearchserviceapplicationproxy
  applicable: SharePoint Server 2010, SharePoint Server 2013, SharePoint Server 2016, SharePoint Server 2019
  title: Get-SPEnterpriseSearchServiceApplicationProxy
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
