### YamlMime:PowershellCmdlet
summary: |-
  Gets hybrid configurations.
module: SharePointServer
links:
- text: Set-SPO365LinkSettings
  href: Set-SPO365LinkSettings.yml
- text: Test-SPO365LinkSettings
  href: Test-SPO365LinkSettings.yml
syntaxes:
- Get-SPO365LinkSettings [-AssignmentCollection <SPAssignmentCollection>] [<CommonParameters>]
examples:
- title: EXAMPLE 1
  code: |-
    $gc = Start-SPAssignment
    Get-SPO365LinkSettings -AssignmentCollection $gc
    Stop-SPAssignment $gc
  description: |-
    This example returns all hybrid configurations.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2013
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.Get-SPO365LinkSettings
name: Get-SPO365LinkSettings
description: |-
  Use the **Get-SPO365LinkSettings** cmdlet to display current hybrid configurations in the farm.
metadata:
  external help file: Microsoft.Office.Server.UserProfiles.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/get-spo365linksettings
  applicable: SharePoint Server 2013, SharePoint Server 2016, SharePoint Server 2019
  title: Get-SPO365LinkSettings
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
