### YamlMime:PowershellCmdlet
summary: |-
  Returns the User Settings Provider Manager.
module: SharePointServer
notes: ""
links:
- text: Get-SPUserSettingsProvider
  href: Get-SPUserSettingsProvider.yml
- text: New-SPUserSettingsProvider
  href: New-SPUserSettingsProvider.yml
- text: Remove-SPUserSettingsProvider
  href: Remove-SPUserSettingsProvider.yml
syntaxes:
- Get-SPUserSettingsProviderManager [-AssignmentCollection <SPAssignmentCollection>] [<CommonParameters>]
examples:
- title: '----------EXAMPLE--------'
  code: |-
    Get-SPUserSettingsProviderManager
  description: |-
    This example returns the User Settings Provider Manager for the farm.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2010
- SharePoint Server 2013
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.Get-SPUserSettingsProviderManager
name: Get-SPUserSettingsProviderManager
description: |-
  Use the Get-SPUserSettingsProviderManager cmdlet to return the User Settings Provider Manager for the farm.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/get-spusersettingsprovidermanager
  applicable: SharePoint Server 2010, SharePoint Server 2013, SharePoint Server 2016, SharePoint Server 2019
  title: Get-SPUserSettingsProviderManager
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
