### YamlMime:PowershellCmdlet
summary: |-
  Returns the uploader.xml and Microsoft.Office.BigData.DataLoader.exe.config files from the Configuration database.
module: SharePointServer
notes: ""
inputs:
- name: <xref href="Microsoft.SharePoint.PowerShell.SPAssignmentCollection" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Get-SPInsightsConfig [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-WhatIf] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    $config = Get-SPInsightsConfig
    $xml = $config.UploaderXml
    $config.UploaderXml = $xml
    $config.Update()
    Stop-SPService -Identity "Microsoft SharePoint Insights"
    Start-SPService -Identity "Microsoft SharePoint Insights"
  description: |-
    This example returns and modifies the config.uploader.xml file. It then restarts the SharePoint Insights service on all servers in order to commit the changes.
  summary: ""
- title: Example 2
  code: |-
    $config = Get-SPInsightsConfig
    $odlExeConfig = $config.OdlExeConfig
    $config.OdlExeConfig = $odlExeConfig
    $config.Update()
    Stop-SPService -Identity "Microsoft SharePoint Insights"
    Start-SPService -Identity "Microsoft SharePoint Insights"
  description: |-
    This example returns and modifies the config.uploader.xml file. It then restarts the SharePoint Insights service on all servers in order to commit the changes.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal. Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management. Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory. When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store. If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.Get-SPInsightsConfig
name: Get-SPInsightsConfig
description: |-
  Returns the uploader.xml and Microsoft.Office.BigData.DataLoader.exe.config files from the Configuration database.
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/get-spinsightsconfig
  applicable: SharePoint Server 2016, SharePoint Server 2019
  title: Get-SPInsightsConfig
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
