### YamlMime:PowershellCmdlet
summary: |-
  Creates a new managed metadata service application.
module: SharePointServer
notes: ""
syntaxes:
- >-
  New-SPMetadataServiceApplication -Name <String> [-AdministratorAccount <String>]
   -ApplicationPool <SPIisWebServiceApplicationPoolPipeBind> [-AssignmentCollection <SPAssignmentCollection>]
   [-CacheTimeCheckInterval <Int32>] [-Confirm] [-DatabaseCredentials <PSCredential>] [-DatabaseName <String>]
   [-DatabaseServer <String>] [-FailoverDatabaseServer <String>] [-FullAccessAccount <String>] [-HubUri <String>]
   [-MaxChannelCache <Int32>] [-PartitionMode] [-ReadAccessAccount <String>] [-RestrictedAccount <String>]
   [-SyndicationErrorReportEnabled] [-WhatIf] [-DisablePartitionQuota] [-DeferUpgradeActions]
   [<CommonParameters>]
- >-
  New-SPMetadataServiceApplication -Name <String> [-AdministratorAccount <String>]
   -ApplicationPool <SPIisWebServiceApplicationPoolPipeBind> [-AssignmentCollection <SPAssignmentCollection>]
   [-CacheTimeCheckInterval <Int32>] [-Confirm] [-DatabaseCredentials <PSCredential>] [-DatabaseName <String>]
   [-DatabaseServer <String>] [-FailoverDatabaseServer <String>] [-FullAccessAccount <String>] [-HubUri <String>]
   [-MaxChannelCache <Int32>] [-PartitionMode] [-ReadAccessAccount <String>] [-RestrictedAccount <String>]
   [-SyndicationErrorReportEnabled] [-WhatIf] -GroupsPerPartition <Int32> -LabelsPerPartition <Int32>
   -PropertiesPerPartition <Int32> -TermSetsPerPartition <Int32> -TermsPerPartition <Int32>
   [-DeferUpgradeActions] [<CommonParameters>]
examples:
- title: '-------------------EXAMPLE 1-------------'
  code: |-
    New-SPMetadataServiceApplication -Name "MetadataServiceApp1" -ApplicationPool "AppPool1" -DatabaseName "MetadataDB1"
  description: |-
    This example creates a new managed metadata service application.
  summary: ""
- title: '-------------------EXAMPLE 2-------------'
  code: |-
    New-SPMetadataServiceApplication -Name "MetadataServiceApp2" -ApplicationPool "AppPool1" -DatabaseName "MetadataDB2" -HubUri "https://sitename" -SyndicationErrorReportEnabled
  description: |-
    This example creates a new managed metadata service application and specifies a content type hub to be used for syndication.
    It also enables error reporting during syndication.
  summary: ""
- title: '-------------------EXAMPLE 3-------------'
  code: |-
    New-SPMetadataServiceApplication -Name "MetadataServiceApp3" -ApplicationPool "AppPool1" -DatabaseName "MetadataDB3" -PartitionMode
  description: |-
    This example creates a new managed metadata service application that is partitioned, for use by sites in a subscription.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AdministratorAccount
  description: |+
    A comma-separated list of user accounts or service accounts in the format \<domain\>\\\<account\> that may create and run the service application.
    The accounts must already exist.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPIisWebServiceApplicationPoolPipeBind" data-throw-if-not-resolved="False" />
  name: ApplicationPool
  isRequired: true
  description: |+
    Specifies an existing IIS application pool in which to run the new managed metadata service application.

    The value must be a GUID that is the identity of an SPServiceApplicationPool object; the name of an existing application pool, or an instance of an SPServiceApplicationPool object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: CacheTimeCheckInterval
  description: |+
    Specifies an interval, in seconds, that a front-end Web Server should wait before asking the application server for changes.
    This value is set per timer job, client application, or Web application.

    The mininum value is 1, and there is no maximum value.
    The default value is 10.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
  name: DatabaseCredentials
  description: |+
    Specifies the PSCredential object that contains the user name and password to be used for database SQL authentication.

    If SQL authentication is to be used, either DatabaseCredentials must be specified or both the DatabaseUserName and DatabasePassword parameters must be set.

    The type must be a valid PSCredential object.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DatabaseName
  description: |+
    Specifies the name of the database to create for the new managed metadata service application.

    The type must be a valid name of a SQL Server database; for example MeatadataDB1.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DatabaseServer
  description: |+
    Specifies the name of the host server for the database specified in DatabaseName.

    The type must be a valid name of a SQL Server database; for example SqlServerHost1.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DeferUpgradeActions
  description: |+
    Specifies if the upgrade process is to be deferred and manually completed.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DisablePartitionQuota
  isRequired: true
  description: |+
    Disables partition quotas.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FailoverDatabaseServer
  description: |+
    Specifies the name of the host server for the failover database server.

    The type must be a valid SQL Server host name; for example, SQLServerHost1.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FullAccessAccount
  description: |+
    Specifies a comma-separated set of application pool accounts in the format \<domain\>\\\<account\> that will be given read/write permission to the managed metadata service's term store and content type gallery.
    The accounts must already exist.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: GroupsPerPartition
  isRequired: true
  description: |+
    Sets the maximum number of Term Groups per partition.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: HubUri
  description: |+
    Specifies the fully qualified URL of the site collection that contains the content type gallery that the service will provide access to.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: LabelsPerPartition
  isRequired: true
  description: |+
    Sets the maximum number of Labels per partition.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MaxChannelCache
  description: |+
    Specifies the maximum number of Windows Communication Foundation (WCF) channels that a front-end Web server should hold open to the application server.

    This value is set per timer job, client application, or Web application.

    The minimum value is 0, and there is no maximum value. The default value is 4.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the service application to create.
    The name can contain a maximum of 128 characters.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PartitionMode
  description: |+
    Specifies that the service application restrict data by subscription.

    Note This property cannot be changed after the service application has been created.

    This property has no effect on SharePoint Server 2019.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: PropertiesPerPartition
  isRequired: true
  description: |+
    Sets the maximum number of Properties per partition.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ReadAccessAccount
  description: |+
    Specifies a comma-separated set of application pool accounts in the format \<domain\>\\\<account\> that will be given read-only permission to the managed metadata service's term store and content type gallery.

    The accounts must already exist.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: RestrictedAccount
  description: |+
    Specifies a comma-separated set of application pool accounts in the format \<domain\>\\\<account\> that will be given permission to read the managed metadata service's term store and content type gallery; and permission to write to open term sets and local term sets and to create new enterprise keywords. 

    The accounts must already exist.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: SyndicationErrorReportEnabled
  description: |+
    Enables reporting of errors when content types are imported.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: TermSetsPerPartition
  isRequired: true
  description: |+
    Sets the maximum number of Term Sets per partition.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: TermsPerPartition
  isRequired: true
  description: |+
    Sets the maximum number of Terms per partition.
  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2010
- SharePoint Server 2013
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.New-SPMetadataServiceApplication
name: New-SPMetadataServiceApplication
description: |-
  Use the `New-SPMetadataServiceApplication` cmdlet to create a new managed metadata service application.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.SharePoint.Taxonomy.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/new-spmetadataserviceapplication
  applicable: SharePoint Server 2010, SharePoint Server 2013, SharePoint Server 2016, SharePoint Server 2019
  title: New-SPMetadataServiceApplication
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
