### YamlMime:PowershellCmdlet
summary: |-
  Creates a new Work Management Service application.
module: SharePointServer
notes: ""
links:
- text: New-SPWorkManagementServiceApplicationProxy
  href: New-SPWorkManagementServiceApplicationProxy.yml
- text: Set-SPWorkManagementServiceApplication
  href: Set-SPWorkManagementServiceApplication.yml
- text: Set-SPWorkManagementServiceApplicationProxy
  href: Set-SPWorkManagementServiceApplicationProxy.yml
syntaxes:
- >-
  New-SPWorkManagementServiceApplication -ApplicationPool <SPIisWebServiceApplicationPoolPipeBind> -Name <String>
   [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-Proxy] [-WhatIf] [<CommonParameters>]
examples:
- title: '------------------EXAMPLE-----------------------'
  code: |-
    New-SPWorkManagementServiceApplication -Name 'Work Management Service Application' -ApplicationPool 'SharePoint Web Services Default'
  description: |-
    This example creates a new Work Management Service Application using the Application Pool named SharePoint Web Services Default.
  summary: ""
parameters:
- type: <xref href="SPIisWebServiceApplicationPoolPipeBind" data-throw-if-not-resolved="False" />
  name: ApplicationPool
  isRequired: true
  description: |+
    Specifies the name of an application pool to use; for example, SharePoint - 1213.
    If no value is specified, the default application pool is used.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal. Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management. Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory. When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store. If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server 2013
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the Work Management Service application to be created.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Proxy
  description: |+
    Specifies whether to add the Work Management Service application to the proxy group.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server 2013
  parameterValueGroup: ""
applicable:
- SharePoint Server 2013
uid: SharePointServer.New-SPWorkManagementServiceApplication
name: New-SPWorkManagementServiceApplication
description: |-
  Use the `New-SPWorkManagementServiceApplication` cmdlet to create a new Work Management Service application.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).

  Note: This functionality has been removed from SharePoint Server 2016, SharePoint Server 2019, but the cmdlet is still present in the product.
metadata:
  external help file: Microsoft.Office.Server.WorkManagement.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/new-spworkmanagementserviceapplication
  applicable: SharePoint Server 2013
  title: New-SPWorkManagementServiceApplication
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
