### YamlMime:PowershellCmdlet
summary: |-
  Adds a new User Settings Provider.
module: SharePointServer
notes: ""
links:
- text: Get-SPUserSettingsProvider
  href: Get-SPUserSettingsProvider.yml
- text: Remove-SPUserSettingsProvider
  href: Remove-SPUserSettingsProvider.yml
- text: Get-SPUserSettingsProviderManager
  href: Get-SPUserSettingsProviderManager.yml
syntaxes:
- >-
  New-SPUserSettingsProvider -AssemblyName <String> -DisplayName <String> -Type <String>
   [-AssignmentCollection <SPAssignmentCollection>] [<CommonParameters>]
examples:
- title: '----------------------- EXAMPLE---------------------------'
  code: |-
    New-SPUserSettingsProvider -DisplayName "My User Settings Provider" -AssemblyName MyProvider.dll -Type MyProvider
  description: |-
    This example adds a user setting provider with a display name of "My User Settings Provider" which uses the MyProvider.dll file.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AssemblyName
  isRequired: true
  description: |+
    Specifies the assembly name for the provider.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayName
  isRequired: true
  description: |+
    Specifies the display name to use for this provider.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Type
  isRequired: true
  description: |+
    Specifies the type name to use for this provider.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2013
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.New-SPUserSettingsProvider
name: New-SPUserSettingsProvider
description: |-
  Use the `New-SPUserSettingsProvider` cmdlet to add a new User Settings Provider to the farm.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/new-spusersettingsprovider
  applicable: SharePoint Server 2013, SharePoint Server 2016, SharePoint Server 2019
  title: New-SPUserSettingsProvider
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
