### YamlMime:PowershellCmdlet
summary: |-
  Creates a proxy for a Project Server Service application.
module: SharePointServer
notes: ""
syntaxes:
- >-
  New-SPProjectServiceApplicationProxy [-Name] <String> -ServiceApplication <PsiServiceApplicationPipeBind>
   [-AssignmentCollection <SPAssignmentCollection>] [<CommonParameters>]
examples:
- title: '-------------------EXAMPLE 1------------------'
  code: |-
    New-SPProjectServiceApplicationProxy -Name PsiApplicationProxy -ServiceApplication PsiApplication
  description: |-
    This example creates a Project Server Service application proxy with the name PsiApplicationProxy for the application PsiApplication.
  summary: ""
- title: '-------------------EXAMPLE 2------------------'
  code: |-
    Get-SPServiceApplication | ?{ $_.Name -eq "PsiApplication" } | New-SPProjectServiceApplicationProxy -Name "PsiApplicationProxy" -Default
  description: |-
    This example creates a Project Server Service application proxy with the name PsiApplicationProxy for the application PsiApplication and adds the proxy to the Default proxy group.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Project Server 2013
  - Project Server 2016
  - Project Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the new proxy.

    The type must be a valid name of a Project Server Service application proxy; for example, ProjectSvcProxy1.

  defaultValue: None
  position: "1"
  aliases: ""
  applicable:
  - Project Server 2013
  - Project Server 2016
  - Project Server 2019
  parameterValueGroup: ""
- type: <xref href="PsiServiceApplicationPipeBind" data-throw-if-not-resolved="False" />
  name: ServiceApplication
  isRequired: true
  description: |+
    Specifies the Project Server Service application to associate with the new proxy.

    The type must be a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; a valid name of a Project Server service application (for example, ProjectWebApp1); or an instance of a valid PsiServiceApplication object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: sa
  applicable:
  - Project Server 2013
  - Project Server 2016
  - Project Server 2019
  parameterValueGroup: ""
applicable:
- Project Server 2013
- Project Server 2016
- Project Server 2019
uid: SharePointServer.New-SPProjectServiceApplicationProxy
name: New-SPProjectServiceApplicationProxy
description: |-
  The `New-SPProjectServiceApplicationProxy` cmdlet creates a proxy for a Project Server Service application.

  For permissions and the most current information about Windows PowerShell for Project Server, see the online documentation at https://go.microsoft.com/fwlink/p/?LinkId=251833 (https://go.microsoft.com/fwlink/p/?LinkId=251833).
metadata:
  external help file: microsoft.office.project.server.stsadmcommandhandler.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/new-spprojectserviceapplicationproxy
  applicable: Project Server 2013, Project Server 2016, Project Server 2019
  title: New-SPProjectServiceApplicationProxy
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
