### YamlMime:PowershellCmdlet
summary: |-
  Creates a Proxy for an Access Services Service Application.
module: SharePointServer
notes: ""
inputs:
- name: <xref href="Microsoft.SharePoint.Administration.SPServiceApplication" data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.SharePoint.PowerShell.SPAssignmentCollection
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  New-SPAccessServicesApplicationProxy [-application] <SPServiceApplication>
   [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-WhatIf] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    $sa = New-SPAccessServicesApplication -DatabaseServer spag.lab.cobaltatom.com -ApplicationPool 'SharePoint Web Services Default' -Name 'Access Services Service Application' -Default
    New-SPAccessServicesApplicationProxy -application $sa
  description: |-
    This example creates an Access Services Application, placing it into the `$sa` variable. Using the `$sa` variable, it is then used to create the Access Services Service Application Proxy.
  summary: ""
parameters:
- type: <xref href="SPServiceApplication" data-throw-if-not-resolved="False" />
  name: application
  isRequired: true
  description: |+
    Specifies the Access Services Service Application to create a proxy for.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal. Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management. Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory. When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store. If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2013
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.New-SPAccessServicesApplicationProxy
name: New-SPAccessServicesApplicationProxy
description: |-
  Creates a Proxy for an Access Services Service Application.
metadata:
  external help file: microsoft.office.access.server.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/new-spaccessservicesapplicationproxy
  applicable: SharePoint Server 2013, SharePoint Server 2016, SharePoint Server 2019
  title: New-SPAccessServicesApplicationProxy
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
