### YamlMime:PowershellCmdlet
summary: |-
  Removes all tenant specific search settings.
module: SharePointServer
notes: ""
syntaxes:
- >-
  Remove-SPEnterpriseSearchTenantConfiguration [-SiteSubscriptionId] <Guid>
   -SearchApplication <SearchServiceApplicationPipeBind> [-AssignmentCollection <SPAssignmentCollection>]
   [-Confirm] [-WhatIf] [<CommonParameters>]
examples:
- title: '------------------EXAMPLE------------------'
  code: |-
    $ssa = Get-SPEnterpriseSearchServiceApplication
    Remove-SPEnterpriseSearchTenantConfiguration -SiteSubscriptionId "00000000-0000-0000-0000-000000000001" -SearchApplication $ssa
  description: |-
    This example uses Remove-SPEnterpriseSearchTenantConfiguration to remove all tenant specific settings from the search service application referenced by $ssa.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal. Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management. Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory. When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store. If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SearchServiceApplicationPipeBind" data-throw-if-not-resolved="False" />
  name: SearchApplication
  isRequired: true
  description: |+
    Specifies the name of the search application that contains the tenant configuration.
    The type must be a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; a valid search application name (for example, SearchApp1); or an instance of a valid SearchServiceApplication object.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: SiteSubscriptionId
  isRequired: true
  description: |+
    Specifies the site subscription of the tenant.
    The type must be a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: Identity
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2013
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.Remove-SPEnterpriseSearchTenantConfiguration
name: Remove-SPEnterpriseSearchTenantConfiguration
description: |-
  The `Remove-SPEnterpriseSearchTenantConfigurationcmdlet` removes all tenant specific search settings.
  The removed settings are: query Rules, result types, result sources, managed metadata, ranking models, search dictionaries, authoritative pages, query suggestion settings, client types and the default search center.
  Use this cmdlet when removing tenants and in conjunction with moving tenants.
  When moving a tenant, copy the tenant configuration from the source to the destination and then use this cmdlet to remove the tenant configuration from the source farm.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.Office.Server.Search.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/remove-spenterprisesearchtenantconfiguration
  applicable: SharePoint Server 2013, SharePoint Server 2016, SharePoint Server 2019
  title: Remove-SPEnterpriseSearchTenantConfiguration
  PlatyPS schema version: 2.0.0
