### YamlMime:PowershellCmdlet
summary: |-
  Deletes the specified service application proxy.
module: SharePointServer
notes: ""
syntaxes:
- >-
  Remove-SPServiceApplicationProxy [-Identity] <SPServiceApplicationProxyPipeBind> [-RemoveData] [-Confirm]
   [-WhatIf] [-AssignmentCollection <SPAssignmentCollection>] [<CommonParameters>]
examples:
- title: '------------------EXAMPLE-----------------------'
  code: |-
    $proxy = Get-SPServiceApplicationProxy | ?{$_.TypeName -eq 'User Profile Service Application Proxy'}
    Remove-SPServiceApplicationProxy $proxy
  description: |-
    This example deletes the User Profile Service Application proxy.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal. Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management. Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory. When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store. If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPServiceApplicationProxyPipeBind" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Specifies the GUID of the service application proxy to remove.

    The type must be a GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: RemoveData
  description: |+
    Deletes all databases and other data associated with the service application proxy.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2010
- SharePoint Server 2013
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.Remove-SPServiceApplicationProxy
name: Remove-SPServiceApplicationProxy
description: |-
  The `Remove-SPServiceApplicationProxy` cmdlet deletes the service application proxy specified by the Identity parameter.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/remove-spserviceapplicationproxy
  applicable: SharePoint Server 2010, SharePoint Server 2013, SharePoint Server 2016, SharePoint Server 2019
  title: Remove-SPServiceApplicationProxy
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
