### YamlMime:PowershellCmdlet
summary: |-
  Resets the settings for the Project Calculation Engine on Project Server.
module: SharePointServer
notes: ""
syntaxes:
- >-
  Reset-SPProjectPCSSettings [-ServiceApplication <PsiServiceApplicationPipeBind>]
   [-AssignmentCollection <SPAssignmentCollection>] [<CommonParameters>]
examples:
- title: '----------------------EXAMPLE-----------------------'
  code: |-
    $sa = Get-SPServiceApplication | ?{$_.TypeName -eq 'Project Application Services'}
    Reset-SPProjectPCSSettings -ServiceApplication $sa
  description: |-
    This cmdlet resets the settings for the Project Calculation Engine that is running on a Project Server Service Application.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Project Server 2013
  - Project Server 2016
  - Project Server 2019
  parameterValueGroup: ""
- type: <xref href="PsiServiceApplicationPipeBind" data-throw-if-not-resolved="False" />
  name: ServiceApplication
  description: |+
    The Project Server service application for which the settings are to be read.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: sa
  applicable:
  - Project Server 2013
  - Project Server 2016
  - Project Server 2019
  parameterValueGroup: ""
applicable:
- Project Server 2013
- Project Server 2016
- Project Server 2019
uid: SharePointServer.Reset-SPProjectPCSSettings
name: Reset-SPProjectPCSSettings
description: |-
  The `Reset-SPProjectPCSSettings` cmdlet lets you reset the settings that control the operations of the Project Calculation Engine on Project Server.
  The cmdlet requires you to identify the Project Server service application.

  For permissions and the most current information about Windows PowerShell for Project Server, see the online documentation at https://go.microsoft.com/fwlink/p/?LinkId=251833 (https://go.microsoft.com/fwlink/p/?LinkId=251833).
metadata:
  external help file: microsoft.office.project.server.stsadmcommandhandler.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/reset-spprojectpcssettings
  applicable: Project Server 2013, Project Server 2016, Project Server 2019
  title: Reset-SPProjectPCSSettings
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
