### YamlMime:PowershellCmdlet
summary: |-
  Removes a security principal from a SPObjectSecurity object.
module: SharePointServer
notes: ""
syntaxes:
- >-
  Revoke-SPObjectSecurity [-Identity] <SPObjectSecurity> [-Principal] <SPClaim> [[-Rights] <String[]>]
   [-AssignmentCollection <SPAssignmentCollection>] [<CommonParameters>]
- >-
  Revoke-SPObjectSecurity [-Identity] <SPObjectSecurity> [-All] [-AssignmentCollection <SPAssignmentCollection>]
   [<CommonParameters>]
examples:
- title: '------------------EXAMPLE------------------'
  code: |-
    $security = Get-SPServiceApplicationSecurity $serviceApp -Admin
    Revoke-SPObjectSecurity $security "domain\user"
    Set-SPServiceApplicationSecurity $serviceApp -Admin $security
  description: |-
    This example retrieves the SPObjectSecurity object corresponding to the administrator ACL on a service application and removes a user from that ACL.
    The removed an administrator for the service application $serviceApp.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: All
  isRequired: true
  description: |+
    Specifies that all security principals are removed from the specified SPObjectSecurity object.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  parameterValueGroup: ""
- type: <xref href="SPObjectSecurity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Specifies the SPObjectSecurity object from which the security principal is removed.
    You can use the `Get-SPServiceApplicationSecurity` cmdlet to get a SPObjectSecurity object .

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  parameterValueGroup: ""
- type: <xref href="SPClaim" data-throw-if-not-resolved="False" />
  name: Principal
  isRequired: true
  description: |+
    Specifies the principal for whom the rights are removed.

    The type must a valid name a principal; for example, Full Control.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Rights
  description: |+
    Specifies the rights of the principal to revoke.

    The type must a valid array of strings that represents the rights of the principal to revoke.

  defaultValue: None
  position: "3"
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  parameterValueGroup: ""
applicable:
- SharePoint Server 2013
- SharePoint Server 2016
uid: SharePointServer.Revoke-SPObjectSecurity
name: Revoke-SPObjectSecurity
description: |-
  This cmdlet contains more than one parameter set.
  You may only use parameters from one parameter set and you may not combine parameters from different parameter sets.
  For more information about how to use parameter sets, see [Cmdlet parameter sets](https://learn.microsoft.com/powershell/scripting/developer/cmdlet/cmdlet-parameter-sets).

  The `Revoke-SPObjectSecurity` cmdlet to remove a security principal, such as a user, from a SPObjectSecurity object.
  An SPObjectSecurity object is a common object that is used to represent the security access control list (ACL) of SharePoint administrative objects, in particular service applications.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at https://go.microsoft.com/fwlink/p/?LinkId=251831 (https://go.microsoft.com/fwlink/p/?LinkId=251831).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/revoke-spobjectsecurity
  applicable: SharePoint Server 2013, SharePoint Server 2016
  title: Revoke-SPObjectSecurity
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
