### YamlMime:PowershellCmdlet
summary: |-
  Sets the parameters of a site subscription.
module: SharePointServer
notes: ""
syntaxes:
- >-
  Set-SPSiteSubscriptionProfileConfig [-Identity] <SPSiteSubscriptionPipeBind>
   [-MySiteHostLocation <SPSitePipeBind>] -ProfileServiceApplicationProxy <SPServiceApplicationProxyPipeBind>
   [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-SynchronizationOU <String>] [-WhatIf]
   [<CommonParameters>]
- >-
  Set-SPSiteSubscriptionProfileConfig [-Identity] <SPSiteSubscriptionPipeBind>
   -MySiteHostLocation <SPSitePipeBind> -ProfileServiceApplicationProxy <SPServiceApplicationProxyPipeBind>
   [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-MySiteManagedPath <SPPrefixPipeBind>]
   [-SiteNamingConflictResolution <String>] [-SynchronizationOU <String>] [-WhatIf] [<CommonParameters>]
examples:
- title: '--------------------EXAMPLE---------------------'
  code: |-
    $sub = Get-SPSiteSubscription http://contoso/my
    Set-SPSiteSubscriptionProfileConfig -Identity $sub -SiteNamingConflictResolution 3 -SynchronizationOU OrgUnit1
  description: |-
    This example sets the parameter of the site subscription SiteNamingConflictResolution to always avoid any conflicts and parameter SynchronizationOU to OrgUnit1.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPSiteSubscriptionPipeBind" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Specifies the proxy of the User Profile Service application that contains the site subscription to update.

    The type must be a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; a valid name of a User Profile Service application proxy (for example, UserProfileSvcProxy1); or an instance of a valid SPServiceApplicationProxy object.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPSitePipeBind" data-throw-if-not-resolved="False" />
  name: MySiteHostLocation
  isRequired: true
  description: |+
    Specifies the site collection where the My Site host for the site subscription is provisioned.

    The type must be a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; or a valid URL, in the form https://server_name; or an instance of a valid SPSite object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPPrefixPipeBind" data-throw-if-not-resolved="False" />
  name: MySiteManagedPath
  description: |+
    Specifies the managed path where personal sites will be created.

    The type must be a valid URL, in the form https://server_name.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPServiceApplicationProxyPipeBind" data-throw-if-not-resolved="False" />
  name: ProfileServiceApplicationProxy
  isRequired: true
  description: |+
    Specifies the name of the proxy for the User Profile Service application.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SiteNamingConflictResolution
  description: |+
    Specifies the format to use to name personal sites.

    Use one of the following integer values:

    1-- Personal site collections to be named after user names without any conflict resolution.
    For example, https://portal_site/location/username/

    2-- Personal site collections to be named after user names with conflict resolution by using domain names.
    For example, .../username/ or .../domain_username/

    3-- Personal site collections to be named using domain and username always to avoid any conflicts.
    For example, https://portal_site/location/domain_username/

    The default value is 1 (do not resolve conflicts).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SynchronizationOU
  description: |+
    Specifies the organizational unit that serves the site subscription.

    The type must be a valid name of an organizational unit; for example, OrgUnit1.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2010
- SharePoint Server 2013
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.Set-SPSiteSubscriptionProfileConfig
name: Set-SPSiteSubscriptionProfileConfig
description: |-
  This cmdlet contains more than one parameter set.
  You may only use parameters from one parameter set and you may not combine parameters from different parameter sets.
  For more information about how to use parameter sets, see [Cmdlet parameter sets](https://learn.microsoft.com/powershell/scripting/developer/cmdlet/cmdlet-parameter-sets).

  The `Set-SPSiteSubscriptionProfileConfig` cmdlet sets the parameters of a site subscription.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.Office.Server.UserProfiles.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/set-spsitesubscriptionprofileconfig
  applicable: SharePoint Server 2010, SharePoint Server 2013, SharePoint Server 2016, SharePoint Server 2019
  title: Set-SPSiteSubscriptionProfileConfig
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
