### YamlMime:PowershellCmdlet
summary: |-
  Sets the properties of a managed metadata service application.
module: SharePointServer
notes: ""
syntaxes:
- >-
  Set-SPMetadataServiceApplication [-Identity] <SPMetadataServiceCmdletPipeBind> [-AdministratorAccount <String>]
   [-ApplicationPool <SPIisWebServiceApplicationPoolPipeBind>] [-AssignmentCollection <SPAssignmentCollection>]
   [-CacheTimeCheckInterval <Int32>] [-Confirm] [-DatabaseCredentials <PSCredential>] [-DatabaseName <String>]
   [-DatabaseServer <String>] [-DoNotUnpublishAllPackages] [-FailoverDatabaseServer <String>]
   [-FullAccessAccount <String>] [-Name <String>] [-RestrictedAccount <String>] [-SyndicationErrorReportEnabled]
   [-HubUri <String>] [-MaxChannelCache <Int32>] [-ReadAccessAccount <String>] [-WhatIf] [-DisablePartitionQuota]
   [<CommonParameters>]
- >-
  Set-SPMetadataServiceApplication [-Identity] <SPMetadataServiceCmdletPipeBind> [-AdministratorAccount <String>]
   [-ApplicationPool <SPIisWebServiceApplicationPoolPipeBind>] [-AssignmentCollection <SPAssignmentCollection>]
   [-CacheTimeCheckInterval <Int32>] [-Confirm] [-DatabaseCredentials <PSCredential>] [-DatabaseName <String>]
   [-DatabaseServer <String>] [-DoNotUnpublishAllPackages] [-FailoverDatabaseServer <String>]
   [-FullAccessAccount <String>] [-Name <String>] [-RestrictedAccount <String>] [-SyndicationErrorReportEnabled]
   [-HubUri <String>] [-MaxChannelCache <Int32>] [-ReadAccessAccount <String>] [-WhatIf]
   -GroupsPerPartition <Int32> -LabelsPerPartition <Int32> -PropertiesPerPartition <Int32>
   -TermSetsPerPartition <Int32> -TermsPerPartition <Int32> [<CommonParameters>]
examples:
- title: '--------------------EXAMPLE 1---------------------'
  code: |-
    $sa = Get-SPMetadataServiceApplication -Identity 'Managed Metadata Service Application'
    Set-SPMetadataServiceApplication -Identity $sa -HubUri 'https://sitename' -SyndicationErrorReportEnabled
  description: |-
    This example adds a content type hub to an existing managed metadata service application.
    It also enables error reporting when content types are imported.
  summary: ""
- title: '--------------------EXAMPLE 2---------------------'
  code: |-
    $sa = Get-SPMetadataServiceApplication -Identity 'Managed Metadata Service Application'
    Set-SPMetadataServiceApplication -Identity $sa -AdministratorAccount 'contoso\username1' -FullAccessAccount 'contoso\AppPoolAccount1,contoso\AppPoolAccount2' -RestrictedAccount 'contoso\AppPoolAccount3,contoso\AppPoolAccount4,contoso\AppPoolAccount5' -ReadAccessAccount 'contoso\AppPoolAccount6'
  description: |-
    This example sets permissions on an existing managed metadata service application.

    If you use Windows PowerShell to set any of the account values, you should set all of them.
    The `Set-SPMetadataServiceApplication` cmdlet first erases all accounts, then adds the accounts that you specified.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AdministratorAccount
  description: |+
    A comma-separated list of user accounts or service accounts in the format \<domain\>\\\<account\> that may create and run the service application.
    The accounts must already exist.

    If a value is set by using this parameter, any existing values for the FullAccessAccount, ReadAccessAccount and RestrictedAccount parameters are removed.
    Consider setting all four parameters at the same time.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPIisWebServiceApplicationPoolPipeBind" data-throw-if-not-resolved="False" />
  name: ApplicationPool
  description: |+
    Specifies an existing IIS application pool in which to run the Web service for the managed metadata service application.

    The value must be a GUID that is the identity of an SPServiceApplicationPool object; the name of an existing application pool; or an instance of a valid SPServiceApplicationPool object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: CacheTimeCheckInterval
  description: |+
    Specifies the interval, in seconds, that a front-end Web server should wait before asking the application server for changes.
    This value is set per timer job, client application, or Web application.

    The mininum value is 1, and there is no maximum value.
    The default value is 10.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
  name: DatabaseCredentials
  description: |+
    Specifies the PSCredential object that contains the user name and password to be used for database SQL authentication.

    If SQL authentication is to be used, either the DatabaseCredentials parameter must be specified or both the DatabaseUserName and DatabasePassword parameters must be set.

    The type must be a valid PSCredential object.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DatabaseName
  description: |+
    Specifies the name of the database that contains the term store for the managed metadata service application.

    The type must be a valid name of a SQL Server database; for example MeatadataDB1.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DatabaseServer
  description: |+
    Specifies the name of the host server for the database specified in DatabaseName.

    The type must be a valid name of a SQL Server database; for example SqlServerHost1.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DisablePartitionQuota
  isRequired: true
  description: |+
    When in partitioned mode, disables the partition quota.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DoNotUnpublishAllPackages
  description: |+
    If this flag is set, the packages will not be unpublished.
    If the HubUri parameter is changed, all content type packages will be unpublished by default.

    If the HubUri parameter is not changed, this flag has no effect.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FailoverDatabaseServer
  description: |+
    Specifies the name of the host server for the failover database server.

    The type must be a valid SQL Server host name; for example, SQLServerHost1.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FullAccessAccount
  description: |+
    Specifies a comma-separated set of application pool accounts in the format \<domain\>\\\<account\> that will be given read/write permission to the managed metadata service's term store and content type gallery.
    The accounts must already exist.

    If a value is set by using this parameter, any existing values for the AdministratorAccount, ReadAccessAccount and RestrictedAccount parameters are removed.
    Consider setting all four parameters at the same time.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: GroupsPerPartition
  isRequired: true
  description: |+
    When in partitioned mode, sets the maximum number of groups per partition.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: HubUri
  description: |+
    Specifies the fully qualified URL of the site collection that contains the content type gallery that the service will provide access to.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPMetadataServiceCmdletPipeBind" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Specifies the managed metadata service application to update.

    The type must be a valid GUID or the name of a valid managed metadata  service application.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: LabelsPerPartition
  isRequired: true
  description: |+
    When in partitioned mode, sets the maximum number of labels per partition.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MaxChannelCache
  description: |+
    Specifies the maximum number of Windows Communication Foundation (WCF) channels that a front-end Web server holds open to the application server.
    This value is set per timer job, client application, or Web application.

    The minimum value is 0, and there is no maximum value.
    The default value is 4.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the new name of the service application.
    The name can contain a maximum of 128 characters.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: PropertiesPerPartition
  isRequired: true
  description: |+
    When in partitioned mode, sets the maximum number of properties per partition.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ReadAccessAccount
  description: |+
    Specifies a comma-separated set of application pool accounts in the format \<domain\>\\\<account\> that will be given read-only permission to the managed metadata service's term store and content type gallery.
    The accounts must already exist.

    If a value is set by using this parameter, any previous values for the FullAccessAccount, RestrictedAccount and AdministratorAccount parameters are removed.
    Consider setting all four parameters at the same time.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: RestrictedAccount
  description: |+
    Specifies a comma-separated set of application pool accounts in the format \<domain\>\\\<account\> that will be given permission to read the managed metadata service's term store and content type gallery and permission to write to open term sets and local term sets and to create new enterprise keywords.
    The accounts must already exist.

    If a value is set by using this parameter, any previous values for the FullAccessAccount, ReadAccessAccount and AdministratorAccount parameters are removed.
    Consider setting all four parameters at the same time.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: SyndicationErrorReportEnabled
  description: |+
    Enables reporting of errors when content types are imported.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: TermSetsPerPartition
  isRequired: true
  description: |+
    When in partitioned mode, sets the maximum number of term sets per partition.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: TermsPerPartition
  isRequired: true
  description: |+
    When in partitioned mode, sets the maximum number of terms per partition.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2010
- SharePoint Server 2013
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.Set-SPMetadataServiceApplication
name: Set-SPMetadataServiceApplication
description: |-
  Use the `Set-SPMetadataServiceApplication` cmdlet to set the properties of a managed metadata service application.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.SharePoint.Taxonomy.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/set-spmetadataserviceapplication
  applicable: SharePoint Server 2010, SharePoint Server 2013, SharePoint Server 2016, SharePoint Server 2019
  title: Set-SPMetadataServiceApplication
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
