### YamlMime:PowershellCmdlet
summary: |-
  Sets the Health Score bucket values for an existing network throttling performance counter for a specified Web application.
module: SharePointServer
notes: ""
syntaxes:
- >-
  Set-SPWebApplicationHttpThrottlingMonitor [-Identity] <SPWebApplicationPipeBind> [-Category] <String>
   [-Counter] <String> [-AssignmentCollection <SPAssignmentCollection>] [-Confirm]
   [-HealthScoreBuckets <Double[]>] [-Instance <String>] [-IsDESC] [-LowerLimit <Double>] [-UpperLimit <Double>]
   [-WhatIf] [<CommonParameters>]
examples:
- title: '------------------EXAMPLE 1------------------'
  code: |-
    C:\PS>$buckets=(2000,1000,500,300,200,100,50,30,20,10)
    Set-SPWebApplicationHttpThrottlingMonitor https://sharepoint -
    Category Memory -Counter 'Available Mbytes' -IsDesc -HealthScoreBuckets $buckets
  description: |-
    This example sets the Health Score bucket values for the Memory\Available Mbytes counter to the array listed for the https://sharepoint Web application.
  summary: ""
- title: '------------------EXAMPLE 2------------------'
  code: |-
    Set-SPWebApplicationHttpThrottlingMonitor https://sharepoint
    0 -Category Memory -Counter 'Available Mbytes' -IsDesc -UpperLimit 3000
  description: |-
    This example sets the upper limit for the Memory\Available Mbytes counter, the highest value in the Health Score buckets, to 3000 for the https://sharepoint Web application.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Category
  isRequired: true
  description: |+
    Specifies the name of the performance counter category.

    The type must be a valid performance counter category in the throttling monitor.
    Use the `Get-SPWebApplicationHttpThrottlingMonitor` cmdlet to return a list of performance counter categories in the throttling monitor.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Counter
  isRequired: true
  description: |+
    Specifies the name of the performance counter.

    The type must be a valid performance counter in the throttling monitor.
    Use the `Get-SPWebApplicationHttpThrottlingMonitor` cmdlet to return a list of performance counters in the throttling monitor.

  defaultValue: None
  pipelineInput: true
  position: "3"
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Double" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: HealthScoreBuckets
  description: |+
    Specifies bucket ranges to use in determining the calculation of the server Health Score for this counter.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: Buckets
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPWebApplicationPipeBind" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Specifies the SharePoint Web application to update.

    The type must be a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; a valid name of a SharePoint Web application (for example, MyOfficeApp1); or an instance of a valid SPWebApplication object.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Specifies the instance of the performance counter.
    The default value is empty.
    If the specified value is invalid, this cmdlet will not run.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: IsDESC
  description: |+
    Specifies that this counter is interpreted in descending order.

    If this parameter is set, Health Score bucket values are interpreted in descending order; for example, set this parameter by using the Memory category and Available Mbytes counter to monitor available memory.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Double" data-throw-if-not-resolved="False" />
  name: LowerLimit
  description: |+
    Specifies the lower limit of the numerical threshold of the specified performance counter.
    The lower limit is the lowest value in the Health Score bucket values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: Lower
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Double" data-throw-if-not-resolved="False" />
  name: UpperLimit
  description: |+
    Specifies the upper limit of the numerical threshold of the specified performance counter.
    The upper limit is the highest value in the Health Score bucket values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: Upper
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2010
- SharePoint Server 2013
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.Set-SPWebApplicationHttpThrottlingMonitor
name: Set-SPWebApplicationHttpThrottlingMonitor
description: |-
  The `Set-SPWebApplicationHttpThrottlingMonitor` cmdlet sets the Health Score bucket values for an existing network throttling performance counter for a specified Web application.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/set-spwebapplicationhttpthrottlingmonitor
  applicable: SharePoint Server 2010, SharePoint Server 2013, SharePoint Server 2016, SharePoint Server 2019
  title: Set-SPWebApplicationHttpThrottlingMonitor
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
