### YamlMime:PowershellCmdlet
summary: |-
  Sets global properties of an existing Access Services application in SharePoint Server.
module: SharePointServer
notes: ""
syntaxes:
- >-
  Set-SPAccessServiceApplication [-Identity] <SPAccessServiceApplicationPipeBind>
   [-AssignmentCollection <SPAssignmentCollection>] [-CacheTimeout <Int32>] [-ColumnsMax <Int32>] [-Confirm]
   [-NonRemotableQueriesAllowed] [-OrderByMax <Int32>] [-OuterJoinsAllowed] [-OutputCalculatedColumnsMax <Int32>]
   [-PrivateBytesMax <Int32>] [-RecordsInTableMax <Int32>] [-RequestDurationMax <Int32>] [-RowsMax <Int32>]
   [-SessionMemoryMax <Int32>] [-SessionsPerAnonymousUserMax <Int32>] [-SessionsPerUserMax <Int32>]
   [-SourcesMax <Int32>] [-TemplateSizeMax <Int32>] [-WhatIf] [-ApplicationLogSizeMax <Int32>]
   [<CommonParameters>]
examples:
- title: '------------EXAMPLE 1------------------'
  code: |-
    Set-SPAccessServiceApplication -identity "MyAccessService" -RequestDurationMax 100
  description: |-
    This example sets the Access Services application named MyAccessService to let requests take up to 100 seconds before they time out.
  summary: ""
- title: '------------EXAMPLE 2------------------'
  code: |-
    Get-SPAccessServiceApplication | Set-SPAccessServiceApplication -SessionsPerUserMax 5
  description: |-
    This example sets every Access Services application in the farm to allow up to five sessions per user on each back-end application server computer on which Access Services runs.

    First, every Access Services application is retrieved and then a new value is set by using the `Set-SPAccessServiceApplication` cmdlet.
  summary: ""
- title: '------------EXAMPLE 3------------------'
  code: |-
    Get-SPAccessServiceApplication | where {$_.RowsMax -gt 50000 } | Set-SPAccessServiceApplication -RowsMax 50000
  description: |-
    This example sets every Access Services application in the farm that allows more than 50,000 rows to be returned from, or used in, a query and then sets the service application to allow up to 50,000 rows only.

    First, every Access Services application that has more than 50,000 rows is retrieved and then a new value is set by using the `Set-SPAccessServiceApplication` cmdlet.
  summary: ""
parameters:
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ApplicationLogSizeMax
  description: |+
    The maximum number of records for an Access Services Application Log list. Valid valies: -1 to maxint. A value of zero means none is allowed. The default value is 3000.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the `Stop-SPAssignment` command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: CacheTimeout
  description: |+
    Specifies the number of seconds that a data cache will remain active on Access services with no user activity.
    Valid values include: -1, cache never times out; 1 to 2073600, cache remains active from 1 second to 24 days.

    The type must be the integers -1, or an integer in the range of 1 to 2073600 (24 days).
    The default value is 300.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ColumnsMax
  description: |+
    Specifies the maximum number of columns that a list involved in a query can contain, or that the output of the query can contain.
    The default value is 30.

    The type must be an integer in the range of 1 to 255.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPAccessServiceApplicationPipeBind" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Specifies the Access Services application to update.

    The type must be a valid name of an Access Services application; for example, AccessSrvApp1; a valid GUID, in the form 12345678-90ab-cdef-1234-567890bcdefgh; or an instance of a valid SPAccessServiceApplication object.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: NonRemotableQueriesAllowed
  description: |+
    Specifies that queries that cannot be sent remotely to the database tier can run.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: OrderByMax
  description: |+
    Specifies the maximum number of Order By clauses in the query.
    The default value is 4.

    The type must be an integer in the range of 1 to 8.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: OuterJoinsAllowed
  description: |+
    Specifies that left and right outer joins are supported.
    Inner joins are always supported.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: OutputCalculatedColumnsMax
  description: |+
    Specifies the maximum number of calculated columns that can be included in the output as a part of the query.
    Calculated columns in the underlying SharePoint list are not included.
    The default value is 10.

    The type must be an integer in the range of 1 to 32.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: PrivateBytesMax
  description: |+
    Specifies the maximum private bytes in megabytes that can be used by Access Services.
    When set to -1 it defaults to 75 percent of physical memory on the machine.
    Valid values: -1, no limit, from 1 to any positive integer.The default value is -1.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: RecordsInTableMax
  description: |+
    Specifies the maximum number of records allowed for a table in the Access Services  application.
    Valid values include: -1, no limit, and 1 to any positive integer.
    The default value is 500000.

    The type must be the integer -1, or an integer in the range of 1 to MaxInt.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: RequestDurationMax
  description: |+
    Specifies the maximum number of seconds that a request to perform an operation can use before the request times out.
    Valid values include: -1, no limit, 1 to 2073600, cache remains active 1 second to 24 days.
    The default value is 30.

    The type must be the integer -1, or an integer in the range of 1 to 2073600 (24 days)

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: RowsMax
  description: |+
    Specifies the maximum number of rows that a list involved in a query can have, or that the output of the query can have.
    The default value is 50000.

    The type must be an integer in the range of 1 to 200000.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: SessionMemoryMax
  description: |+
    Specifies the maximum allowable size, in megabytes, of an individual session.
    Valid values include: 0, disable property, 1 to 4095.
    The default value is 64.

    The type must be the integer 0, or an integer in the range of 1 to 4095.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: SessionsPerAnonymousUserMax
  description: |+
    The maximum number of sessions allowed per user.
    If this maximum is reached, the oldest session will be deleted when a new session is started.
    Valid values include: -1, no limit, and 1 to any positive integer.
    The default value is 10.

    The integer -1, or an integer in the range of 1 to MaxInt

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: SessionsPerUserMax
  description: |+
    Specifies the maximum number of sessions allowed per user.
    If this maximum is reached, the oldest session will be deleted when a new session is started.
    Valid values include: -1, no limit, and 1 to any positive integer.
    The default value is 10.

    The integer -1, or an integer in the range of 1 to MaxInt.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: SourcesMax
  description: |+
    Specifies the maximum number of lists that may be used as input to a query at one time.
    The default value is 8.

    The type must be an integer in the range of 1 to 20.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: TemplateSizeMax
  description: |+
    The maximum allowable size in megabytes (MB) allowed for Access templates (.accdt files) uploaded into the solution gallery.
    Valid values: -1, no limit, from 1 to any positive integer.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2010
- SharePoint Server 2013
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.Set-SPAccessServiceApplication
name: Set-SPAccessServiceApplication
description: |-
  The `Set-SPAccessServiceApplication` cmdlet sets the global runtime properties of an existing Access Services application in SharePoint Server.
  The changes made to the properties by using this cmdlet affect all machines in the farm on which this Access Services application runs.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: microsoft.office.access.services.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/set-spaccessserviceapplication
  applicable: SharePoint Server 2010, SharePoint Server 2013, SharePoint Server 2016, SharePoint Server 2019
  title: Set-SPAccessServiceApplication
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
