### YamlMime:PowershellCmdlet
summary: |-
  Do Not Use
module: SharePointServer
notes: ""
inputs:
- name: <xref href="Microsoft.SharePoint.PowerShell.SPServiceApplicationPipeBind" data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.SharePoint.PowerShell.SPAssignmentCollection
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Upgrade-SPAppManagementServiceApplication [[-Identity] <SPServiceApplicationPipeBind>]
   [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-DatabaseIds <Guid[]>] [-WhatIf]
   [<CommonParameters>]
- >-
  Upgrade-SPAppManagementServiceApplication [-AssignmentCollection <SPAssignmentCollection>] [-Confirm]
   [-DatabaseIds <Guid[]>] [-Name <String>] [-WhatIf] [<CommonParameters>]
examples:
- title: '--------------EXAMPLE-----------------'
  code: |-
    Do Not Use
  description: ""
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Do Not Use

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: DatabaseIds
  description: |+
    Do Not Use

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPServiceApplicationPipeBind" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Do Not Use

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Do Not Use

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.Upgrade-SPAppManagementServiceApplication
name: Upgrade-SPAppManagementServiceApplication
description: |-
  Do Not Use
metadata:
  external help file: Microsoft.SharePoint.PowerShell.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/upgrade-spappmanagementserviceapplication
  applicable: SharePoint Server 2016, SharePoint Server 2019
  title: Upgrade-SPAppManagementServiceApplication
  PlatyPS schema version: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
