### YamlMime:PowershellCmdlet
summary: |-
  Creates a new SharePoint Online management Application Proxy Name
module: Microsoft.Online.SharePoint.PowerShell
links:
- text: Introduction to the SharePoint Online management shell
  href: https://support.office.com/en-us/article/introduction-to-the-sharepoint-online-management-shell-c16941c3-19b4-4710-8056-34c034493429
- text: SharePoint Online Management Shell Download
  href: https://www.microsoft.com/en-US/download/details.aspx?id=35588
- text: Get-SPOAppErrors
  href: Get-SPOAppErrors.yml
- text: Start-SPOUserAndContentMove
  href: Start-SPOUserAndContentMove.yml
- text: Full Download to Hybrid Scripts
  href: https://www.microsoft.com/en-us/download/confirmation.aspx?id=51490
syntaxes:
- >-
  New-SPOnlineApplicationPrincipalManagementServiceApplicationProxy
   [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-DefaultProxyGroup] -Name <String>
   -OnlineTenantUri <String> [-WhatIf] [<CommonParameters>]
examples:
- title: EXAMPLE 1
  code: |-
    New-SPOnlineApplicationPrincipalManagementServiceApplicationProxy -Name $SPO_MANAGEMENT_APPPROXY_NAME -OnlineTenantUri $PortalUrl -DefaultProxyGroup
  description: |-
    Found the proxies for the tenant on the variable $PortalUrl on the Default Proxy Group.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    After the creation of the new Principal Management Service Application proxy assign it to the collection.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DefaultProxyGroup
  description: |+
    Search Proxies on the default Proxy Group

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    SPO Management AppProxy Name.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: OnlineTenantUri
  isRequired: true
  description: |+
    Define the online Tenant URI.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  parameterValueGroup: ""
applicable:
- SharePoint Server 2013
- SharePoint Server 2016
uid: Microsoft.Online.SharePoint.PowerShell.New-SPOnlineApplicationPrincipalManagementServiceApplicationProxy
name: New-SPOnlineApplicationPrincipalManagementServiceApplicationProxy
description: |-
  This Cmdlet is used to create a new Application Proxy name, for example usually when you run [this script](https://www.microsoft.com/en-us/download/confirmation.aspx?id=51490) you onboard your SharePoint Online (SPO) tenant and your SharePoint server cloud SSA to cloud hybrid search.
metadata:
  external help file: sharepointonline.xml
  Module Name: Microsoft.Online.SharePoint.PowerShell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-online/new-sponlineapplicationprincipalmanagementserviceapplicationproxy
  applicable: SharePoint Server 2013, SharePoint Server 2016
  title: New-SPOnlineApplicationPrincipalManagementServiceApplicationProxy
  PlatyPS schema version: 2.0.0
  author: trent-green
  ms.author: trgreen
  ms.reviewer: ""
